#Embedded file name: localization\const.py
"""
Defines constants related to the localization framework
"""
LOCALE_SHORT_ENGLISH = 'en-us'
LOCALE_SHORT_GERMAN = 'de'
LOCALE_SHORT_FRENCH = 'fr'
LOCALE_SHORT_RUSSIAN = 'ru'
LOCALE_SHORT_JAPANESE = 'ja'
LOCALE_SHORT_CHINESE = 'zh'
PRIMARY_LANGUAGE_ID = 'en-us'
DATATYPE_FSD = 0
DATATYPE_BSD = 1
CODE_UNIVERSAL = 'Universal'
REGISTERED_TYPE_BSD = 1
REGISTERED_TYPE_DYNAMIC = 2
GENDER_MALE = 0
GENDER_FEMALE = 1
GENDER_NEUTER = 2
GENDERS_EXACTLY_ONE_MALE = 0
GENDERS_EXACTLY_ONE_FEMALE = 1
GENDERS_AT_LEAST_ONE_MALE = 2
GENDERS_ALL_FEMALE = 3
GENDERS_UNDEFINED = 4
DEFAULT_MAXIMUM_DECIMAL_PLACES = 12
DEFAULT_LEADING_ZEROES = 0
PICKLE_LABELS_MESSAGEID = 'messageID'
PICKLE_LABELS_FULLPATH = 'FullPath'
PICKLE_LABELS_LABEL = 'label'
SYSTEM_LANGUAGE = ''
IMPORTANT_EN_OVERRIDE = 1
HIGHLIGHT_IMPORTANT_MARKER = '*'
