#Embedded file name: paperDoll\prePassFixup.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.paperDoll.paperDollPrePassFixup import AddDepthNormalAreasToStandardMesh
from eve.client.script.paperDoll.paperDollPrePassFixup import AddPrepassAreasToAvatar
from eve.client.script.paperDoll.paperDollPrePassFixup import FindMaterialID
from eve.client.script.paperDoll.paperDollPrePassFixup import MATERIAL_ID_EXACT
from eve.client.script.paperDoll.paperDollPrePassFixup import MATERIAL_ID_TRANSPARENT_HACK_EXACT
