#Embedded file name: paperDoll\renderDrivers.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.paperDoll.renderDrivers import RenderDriver
from eve.client.script.paperDoll.renderDrivers import RenderDriverCollapsePLP
from eve.client.script.paperDoll.renderDrivers import RenderDriverNCC
from eve.client.script.paperDoll.renderDrivers import RenderDriverPLP
