#Embedded file name: paperDoll\resData.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.common.script.paperDoll.paperDollResData import Entry
from eve.common.script.paperDoll.paperDollResData import GenderData
from eve.common.script.paperDoll.paperDollResData import ResData
from eve.common.script.paperDoll.paperDollResData import SourceGeo
from eve.common.script.paperDoll.paperDollResData import SourceMap
