#Embedded file name: eve/client/script/environment/effects\effectConsts.py
FX_MERGE_GUID = 2
FX_MERGE_SHIP = 4
FX_MERGE_MODULE = 8
FX_MERGE_TARGET = 16
FX_TF_NONE = 0
FX_TF_POSITION_BALL = 2
FX_TF_POSITION_MODEL = 128
FX_TF_POSITION_TARGET = 4
FX_TF_ROTATION_BALL = 8
FX_TF_SCALE_SYMMETRIC = 16
FX_TF_SCALE_BOUNDING = 32
FX_TF_SCALE_RADIUS = 64
