#Embedded file name: ai.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.script.entities.AI.aimingCommon import aimingCommon
from carbon.common.script.entities.AI.perceptionCommon import perceptionCommon
