#Embedded file name: assets.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.ui.shared.assetsSearch import ParseString
from eve.client.script.ui.shared.assetsSearch import SearchBox
