#Embedded file name: baseEventLog.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.common.script.sys.baseEventLog import BaseEventLogSvc
from eve.common.script.sys.baseEventLog import EventLogChannel
from eve.common.script.sys.baseEventLog import FmtEventLogDate
