#Embedded file name: component.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.client.script.graphics.boxLightClient import BoxLightClientComponent
from carbon.client.script.graphics.cylinderLightClient import CylinderLightClientComponent
from carbon.client.script.graphics.directionalLightClient import DirectionalLightClientComponent
from carbon.client.script.graphics.highlightClient import HighlightComponent
from carbon.client.script.graphics.interiorPlaceableClient import InteriorPlaceableClientComponent
from carbon.client.script.graphics.interiorStaticClient import InteriorStaticClientComponent
from carbon.client.script.graphics.lensFlareClient import LensFlareComponent
from carbon.client.script.graphics.lightAnimationComponent import LightAnimationComponent
from carbon.client.script.graphics.loadedLightClient import LoadedLightClientComponent
from carbon.client.script.graphics.occluderClient import OccluderClientComponent as LightClientComponent
from carbon.client.script.graphics.particleObjectClient import ParticleObjectComponent
from carbon.client.script.graphics.physicalPortalClient import PhysicalPortalClientComponent
from carbon.client.script.graphics.pointLightClient import PointLightClientComponent
from carbon.client.script.graphics.spotLightClient import SpotLightClientComponent
from carbon.client.script.graphics.uiDesktopComponent import UIDesktopComponent
from carbon.client.script.graphics.uvPickingClient import UVPickingComponent
from eve.client.script.entities.spawnLocationClient import SpawnLocationComponent
from eve.client.script.graphics.shipHologramComponent import ShipHologramComponent as shipHologram
