#Embedded file name: crimewatchTimers.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.ui.crimewatch.crimewatchHints import EngagementEntry
from eve.client.script.ui.crimewatch.crimewatchHints import EngagementTimerHint
from eve.client.script.ui.crimewatch.crimewatchTimers import Timer
from eve.client.script.ui.crimewatch.crimewatchTimers import TimerContainer
from eve.client.script.ui.crimewatch.crimewatchHints import TimerHint
from eve.client.script.ui.crimewatch.crimewatchTimers import TimerType
