#Embedded file name: dbutil.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.script.sys.crowset import CFilterRowset
from carbon.common.script.sys.crowset import CFilterRowsetDisk
from carbon.common.script.sys.crowset import CIndexedRowset
from carbon.common.script.sys.crowset import CIndexedRowsetDisk
from carbon.common.script.sys.crowset import CRowset
from carbon.common.script.sys.crowset import CRowsetDiskBase
from carbon.common.script.sys.crowset import LinearDict
from carbon.common.script.sys.crowset import LoadRowset
from carbon.common.script.sys.crowset import SaveRowset
from carbon.common.script.util.dbutil import ExecuteProcInBlocks
from carbon.common.script.util.dbutil import SQLStringify
from carbon.common.script.util.dbutil import TuplesToCSVStrings
from eve.common.script.sys.rowset import RowDict
from eve.common.script.sys.rowset import RowList
