#Embedded file name: debugShapes.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.client.script.graphics.debugRenderClient import DebugBox
from carbon.client.script.graphics.debugRenderClient import DebugCapsule
from carbon.client.script.graphics.debugRenderClient import DebugCone
from carbon.client.script.graphics.debugRenderClient import DebugCylinder
from carbon.client.script.graphics.debugRenderClient import DebugRay
from carbon.client.script.graphics.debugRenderClient import DebugSphere
from carbon.client.script.graphics.debugRenderClient import DebugText
