#Embedded file name: decisionProcs.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.script.entities.AI.decisionProcs import ActionPopupMenu
from carbon.common.script.entities.AI.decisionProcs import ForceDecisionTreeToRootFunc as ForceDecisionTreeToRoot
