#Embedded file name: dna.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.devtools.script.dna import InfoPanel
from eve.devtools.script.dna import Popup
from eve.devtools.script.dna import Ship
