#Embedded file name: dogmaXP.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.common.script.dogma.fitting import LauncherFittedEffect
from eve.common.script.dogma.fitting import SubSystemFittedEffect
from eve.common.script.dogma.fitting import TurretFittedEffect
from eve.common.script.dogma.fitting import UpgradeFittedEffect
from eve.common.script.dogma.hardPointModifierEffect import HardpointModifierEffect as HardPointModifier
from eve.common.script.dogma.slotModifier import SlotModifier
