#Embedded file name: entityCommon.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.script.entities.entityCommon import GetComponentName
from carbon.common.script.entities.entityCommon import GetDBInitValuesFromValue
from carbon.common.script.entities.entityCommon import GetIngredientInitialValue
from carbon.common.script.entities.entityCommon import GetParentTypeString
