#Embedded file name: fontflags.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbonui.services.font import b
from carbonui.services.font import i
from carbonui.services.font import u
