#Embedded file name: fontConst.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbonui.fontconst import DEFAULT_FONTSIZE
from carbonui.fontconst import DEFAULT_LETTERSPACE
from carbonui.fontconst import DEFAULT_LINESPACE
from carbonui.fontconst import DEFAULT_UPPERCASE
from carbonui.fontconst import FONTFAMILY_PER_WINDOWS_LANGUAGEID
from carbonui.fontconst import STYLE_DEFAULT
from carbonui.fontconst import SYSTEMFONTROOT
