#Embedded file name: godma.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.environment.godma import EffectWrapper
from eve.client.script.environment.godma import ItemWrapper
from eve.client.script.environment.godma import MODULE_NOT_OVERLOADED
from eve.client.script.environment.godma import MODULE_OVERLOADED
from eve.client.script.environment.godma import MODULE_PENDING_OVERLOADING
from eve.client.script.environment.godma import MODULE_PENDING_STOPOVERLOADING
from eve.client.script.environment.godma import StateManager
