#Embedded file name: gpcs.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.script.net.BroadcastStuffGPCS import CoreBroadcastStuff
from carbon.common.script.net.ExceptionMappingGPCS import ExceptionMappingGPCS as ExceptionMapping
from carbon.common.script.net.ExceptionMappingGPCS import TRANSPORT_CLOSED_MESSAGES
from carbon.common.script.net.ExceptionWrapperGPCS import ExceptionWrapper
from carbon.common.script.net.ObjectCallGPCS import MachoBoobyTrap
from carbon.common.script.net.ObjectCallGPCS import ObjectCall
from carbon.common.script.net.ResolveGPCS import ResolveGPCS as Resolve
from carbon.common.script.net.ServiceCallGPCS import CoreServiceCall
from carbon.common.script.net.SessionChangeGPCS import SessionChange
from eve.common.script.net.eveBroadcastStuffGPCS import BroadcastStuff
from eve.common.script.net.eveServiceCallGPCS import ServiceCall
