#Embedded file name: httpApps.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.script.net.httpApps import MapController
from carbon.common.script.net.httpApps import NodeController
from carbon.common.script.net.httpApps import PolarisController
from carbon.common.script.net.httpApps import ServerPageHandler
