#Embedded file name: httpUtil.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.script.net.httpUtil import ToComplexJSON
from carbon.common.script.net.httpUtil import ToJSON
