#Embedded file name: igsUtil.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.script.util.igsUtil import AggregateEvent
from carbon.common.script.util.igsUtil import IDX_CHAR1
from carbon.common.script.util.igsUtil import IDX_CHAR2
from carbon.common.script.util.igsUtil import IDX_CHAR3
from carbon.common.script.util.igsUtil import IDX_DATETIME
from carbon.common.script.util.igsUtil import IDX_FLOAT1
from carbon.common.script.util.igsUtil import IDX_FLOAT2
from carbon.common.script.util.igsUtil import IDX_FLOAT3
from carbon.common.script.util.igsUtil import IDX_INT1
from carbon.common.script.util.igsUtil import IDX_INT2
from carbon.common.script.util.igsUtil import IDX_INT3
from carbon.common.script.util.igsUtil import IDX_ITEMID
from carbon.common.script.util.igsUtil import IDX_ITEMID2
from carbon.common.script.util.igsUtil import LISTINDEXDICT
from carbon.common.script.util.igsUtil import MAXEVENTS
