#Embedded file name: infoPanel.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.ui.shared.infoPanels.infoPanelConst import LEFTPAD
from eve.client.script.ui.shared.infoPanels.infoPanelConst import MODE_COLLAPSED
from eve.client.script.ui.shared.infoPanels.infoPanelConst import MODE_COMPACT
from eve.client.script.ui.shared.infoPanels.infoPanelConst import MODE_NORMAL
from eve.client.script.ui.shared.infoPanels.infoPanelConst import PANELTYPES
from eve.client.script.ui.shared.infoPanels.infoPanelConst import PANELWIDTH
from eve.client.script.ui.shared.infoPanels.infoPanelConst import PANEL_FACTIONAL_WARFARE
from eve.client.script.ui.shared.infoPanels.infoPanelConst import PANEL_INCURSIONS
from eve.client.script.ui.shared.infoPanels.infoPanelConst import PANEL_LOCATION_INFO
from eve.client.script.ui.shared.infoPanels.infoPanelConst import PANEL_MISSIONS
from eve.client.script.ui.shared.infoPanels.infoPanelConst import PANEL_PLANETARY_INTERACTION
from eve.client.script.ui.shared.infoPanels.infoPanelConst import PANEL_ROUTE
