#Embedded file name: lg.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.client.script.util.lg import Error
from carbon.client.script.util.lg import Info
from carbon.client.script.util.lg import Warn
from carbon.client.script.util.lg import _Test
