#Embedded file name: lightfxsvc.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.ui.extras.lightfxsvc import BlinkingLedEffect
from eve.client.script.ui.extras.lightfxsvc import BreathingLedEffect
from eve.client.script.ui.extras.lightfxsvc import LedEffect
