#Embedded file name: linalg.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.script.util.linalg import Matrix
from carbon.common.script.util.linalg import Vector
