#Embedded file name: log.py
"""This is an autogenerated file to mimic the nasty namespace."""
from logmodule import *
from carbon.common.script.util.logUtil import LogError
from carbon.common.script.util.logUtil import LogException
from carbon.common.script.util.logUtil import LogInfo
from carbon.common.script.util.logUtil import LogMixin
from carbon.common.script.util.logUtil import LogNotice
from carbon.common.script.util.logUtil import LogWarn
from carbon.common.script.util.logUtil import logger
from carbon.common.script.util.logUtil import supersafestr
