#Embedded file name: lpstore.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.ui.station.lpstore import LPStoreButton
from eve.client.script.ui.station.lpstore import LPStoreEntryLabel
from eve.client.script.ui.station.lpstore import LPStoreHeaderLabel
from eve.client.script.ui.station.lpstore import LPStoreLabel
from eve.client.script.ui.station.lpstore import RequiredItem
