#Embedded file name: paperDollUtil.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.common.script.util.paperDollBloodLineAssets import bloodlineAssets
from eve.common.script.util.paperDollUtil import BuildPaperdollProcedureArgs
from eve.common.script.util.paperDollUtil import CreateRandomDoll
from eve.common.script.util.paperDollUtil import CreateRandomDollNoClothes
from eve.common.script.util.paperDollUtil import FACIAL_POSE_PARAMETERS
from eve.common.script.util.paperDollUtil import HasRequiredClothing
from eve.common.script.util.paperDollUtil import bloodlineAssets
