#Embedded file name: planetUtil.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.common.script.planet.planetUtil import IterCorrectedScanGrid
from eve.common.script.planet.planetUtil import MATH_2PI
from eve.common.script.planet.planetUtil import MATH_PI_DIV_2
