#Embedded file name: sandbox.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.script.sys.sandbox import eval_fingerprinted as eval
from carbon.common.script.sys.sandbox import eval_constant
from carbon.common.script.sys.sandbox import eval_expression
from carbon.common.script.sys.sandbox import fingerprint
