#Embedded file name: screens.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.ui.station.captainsquarters.screens import cqagentfinderscreen
from eve.client.script.ui.station.captainsquarters.screens import cqmainscreen
from eve.client.script.ui.station.captainsquarters.screens import cqpiscreen
from eve.client.script.ui.station.captainsquarters.screens import stationlogo
