#Embedded file name: spiffy.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.devtools.script.spiffy import CreateMenu
from eve.devtools.script.spiffy import ENTRY_HASSUBMENU
from eve.devtools.script.spiffy import ENTRY_ISDYNAMIC
from eve.devtools.script.spiffy import ENTRY_VADJUST
from eve.devtools.script.spiffy import Menu
from eve.devtools.script.spiffy import MenuEntry
from eve.devtools.script.spiffy import MenuHeader
from eve.devtools.script.spiffy import Scroll
from eve.devtools.script.spiffy import Window
