#Embedded file name: StacklessSocketServer.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.script.net.StacklessSocketServer import UThreadingMixIn
from carbon.common.script.net.StacklessSocketServer import UThreadingTCPServer
