#Embedded file name: tutorial.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.common.script.entities.proximityOpenTutorialComponent import ProximityOpenTutorialComponent
from eve.client.script.ui.services.tutoriallib import TutorialColor
from eve.client.script.ui.services.tutoriallib import TutorialConstants
from eve.client.script.ui.shared.spaceObjectUiPointer import SpaceObjectUiPointerBracket
