#Embedded file name: uiEventListener.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.client.script.util.uiEventListener import BaseEventPanel
from carbon.client.script.util.uiEventListener import HelpPanel
from carbon.client.script.util.uiEventListener import UIEventPanel
from carbon.client.script.util.uiEventListener import UIGlobalEventPanel
from carbon.client.script.util.uiEventListener import UIShortcutPanel
from carbon.client.script.util.uiEventListener import WindowsEventPanel
