#Embedded file name: warObject.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.ui.services.wars.war_cso_base import BaseWarObject as base
from eve.client.script.ui.services.wars.war_cso_wars import WarsO as wars
