#Embedded file name: webroutines.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.util.webtools import DirectoryRoutines
from eve.client.script.util.webtools import LoggingRoutines
