#Embedded file name: worldspaceCustomization.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.ui.station.worldspaceCustomization import ApplyWorldspaceCustomization
from eve.client.script.ui.station.worldspaceCustomization import MultiplyColorValue
from eve.client.script.ui.station.worldspaceCustomization import SetShaderMaterialValue
from eve.client.script.ui.station.worldspaceCustomization import UpdateCylendricalLights
from eve.client.script.ui.station.worldspaceCustomization import UpdateEnlightenTexture
from eve.client.script.ui.station.worldspaceCustomization import UpdateFlares
from eve.client.script.ui.station.worldspaceCustomization import UpdateShaderParameters
from eve.client.script.ui.station.worldspaceCustomization import UpdateSpotPointLights
from eve.client.script.ui.station.worldspaceCustomizationDefinitions import DEFAULT_GALLENTE
from eve.client.script.ui.station.worldspaceCustomizationDefinitions import QUAFE_OWNER
from eve.client.script.ui.station.worldspaceCustomizationDefinitions import themeSettings
