#Embedded file name: xmlwriter.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.script.util.dhtmlxwriters import DHtmlXDataWriter
from carbon.common.script.util.dhtmlxwriters import DHtmlXData_Default
from carbon.common.script.util.dhtmlxwriters import DHtmlXData_Grid
from carbon.common.script.util.dhtmlxwriters import DHtmlXData_Tree
from carbon.common.script.util.dhtmlxwriters import DHtmlXData_TreeGrid
from carbon.common.script.util.dhtmlxwriters import DHtmlXElement
from carbon.common.script.util.xmlwriters import XmlWriter
