#Embedded file name: eve/client/script/ui/services/menuSvcExtras\menuConsts.py
import carbonui.const as uiconst
MOUSEBUTTONS = (uiconst.MOUSELEFT,
 uiconst.MOUSERIGHT,
 uiconst.MOUSEMIDDLE,
 uiconst.MOUSEXBUTTON1,
 uiconst.MOUSEXBUTTON2)
CONTAINERGROUPS = (const.groupWreck,
 const.groupCargoContainer,
 const.groupSpawnContainer,
 const.groupSpewContainer,
 const.groupSecureCargoContainer,
 const.groupAuditLogSecureContainer,
 const.groupFreightContainer,
 const.groupDeadspaceOverseersBelongings,
 const.groupMissionContainer)

def GetReasonsDict():
    """
        returns a dictionary with the explanation text why an option is not available.
        The ones that are commented out are hard coded strings and are probably never displayed.
        During testing we should find out if they are used, and if they are mls strings
        should be made for them
    """
    reasonDict = {'notInSpace': 'UI/Menusvc/MenuHints/YouAreNotInSpace',
     'notInSystem': 'UI/Menusvc/MenuHints/LocationNotInSystem',
     'notInApproachRange': 'UI/Menusvc/MenuHints/NotInApproachRange',
     'cantKeepInRange': 'UI/Menusvc/MenuHints/CannotKeepInRange',
     'notStation': 'UI/Menusvc/MenuHints/IsNotStation',
     'notStargate': 'UI/Menusvc/MenuHints/IsNotStargate',
     'notWithinMaxJumpDist': 'UI/Menusvc/MenuHints/NotWithingMaxJumpDist',
     'severalJumpDest': 'UI/Menusvc/MenuHints/SeveralJumpDestinations',
     'cantUseGate': 'UI/Menusvc/MenuHints/ShipNotAllowedToUseGate',
     'notWarpGate': 'UI/Menusvc/MenuHints/NotAccelerationGate',
     'notCloseEnoughToWH': 'UI/Menusvc/MenuHints/NotCloseEnoughToEnterWormhole',
     'notInLookingRange': 'UI/Menusvc/MenuHints/OutsideLookingRange',
     'notWithinMaxTransferRange': 'UI/Menusvc/MenuHints/NotWithinMaxTranferDistance',
     'notInTargetingRange': 'UI/Menusvc/MenuHints/NotInTargetRange',
     'notSpacePig': 'UI/Menusvc/MenuHints/IsNotAnAgent',
     'cantScoopDrone': 'UI/Menusvc/MenuHints/DroneCannotBeScooped',
     'droneNotInScooopRange': 'UI/Menusvc/MenuHints/DroneOutsideScoopRange',
     'notWithinMaxConfigRange': 'UI/Menusvc/MenuHints/NotWithinMaxConfigDist',
     'notOwnedByYouOrCorpOrAlliance': 'UI/Corporations/Common/NotOwnedByYouOrCorpOrAlliance',
     'dontControlDrone': 'UI/Menusvc/MenuHints/DoNotControlDrone',
     'droneIncapacitated': 'UI/Menusvc/MenuHints/DroneIncapacitated',
     'dontOwnDrone': 'UI/Menusvc/MenuHints/DoNotOwnDrone',
     'notInWarpRange': 'UI/Menusvc/MenuHints/NotInWarpRange',
     'cantWarpTo': 'UI/Menusvc/MenuHints/CantWarpTo',
     'inCapsule': 'UI/Menusvc/MenuHints/YouAreInCapsule',
     'inWarp': 'UI/Menusvc/MenuHints/YouAreInWarp',
     'pilotInShip': 'UI/Menusvc/MenuHints/ShipAlreadyPiloted',
     'inWarpRange': 'UI/Menusvc/MenuHints/InWarpRange',
     'beingTargeted': 'UI/Menusvc/MenuHints/BeingTargeted',
     'isMyShip': 'UI/Menusvc/MenuHints/IsYourShip',
     'isNotMyShip': 'UI/Menusvc/MenuHints/NotYourShip',
     'autopilotActive': 'UI/Menusvc/MenuHints/AutopilotActive',
     'autopilotNotActive': 'UI/Menusvc/MenuHints/AutopilotNotActive',
     'isLookingAtItem': 'UI/Menusvc/MenuHints/AlreadyLookingAtItem',
     'notLookingAtItem': 'UI/Menusvc/MenuHints/NotLookingAtItem',
     'alreadyTargeted': 'UI/Menusvc/MenuHints/AlreadyTargeted',
     'notInTargets': 'UI/Menusvc/MenuHints/NotInTargets',
     'badGroup': 'UI/Menusvc/MenuHints/BadGroupForAction',
     'thisIsNot': 'UI/Menusvc/MenuHints/ThisIsNot'}
    return reasonDict


def GetMultiFunctionList():
    multiFunctions = ['UI/Inventory/ItemActions/MultiSell',
     'UI/Inventory/ItemActions/Repackage',
     'UI/Contracts/BreakContract',
     'UI/Inventory/ItemActions/Refine',
     'UI/Inventory/ItemActions/Reprocess',
     'UI/Drones/LaunchDrones',
     'UI/Inventory/ItemActions/TrashIt',
     'UI/Inventory/ItemActions/SplitStack',
     'UI/SkillQueue/AddSkillMenu/TrainNowToLevel1',
     'UI/SkillQueue/InjectSkill',
     'UI/Inventory/ItemActions/PlugInImplant',
     'UI/Inventory/ItemActions/AssembleContainer',
     'UI/Inventory/ItemActions/OpenContainer',
     'UI/Inventory/ItemActions/AssembleShip',
     'UI/Inventory/ItemActions/FitToActiveShip',
     'UI/Commands/OpenDroneBay',
     'UI/Commands/OpenCargoHold',
     'UI/Inventory/ItemActions/LaunchForSelf',
     'UI/Inventory/ItemActions/LaunchForCorp',
     'UI/Inventory/ItemActions/Jettison',
     'take out trash',
     'UI/Drones/EngageTarget',
     'UI/Drones/MineWithDrone',
     'UI/Drones/MineRepeatedly',
     'UI/Drones/ReturnDroneAndOrbit',
     'UI/Drones/ReturnDroneToBay',
     'UI/Drones/DelegateDroneControl',
     'UI/Drones/DroneAssist',
     'UI/Drones/DroneGuard',
     'UI/Drones/ReturnDroneControl',
     'UI/Drones/AbandonDrone',
     'UI/Drones/ScoopDroneToBay',
     'UI/Inventory/ItemActions/LockItem',
     'UI/Inventory/ItemActions/UnlockItem',
     'UI/Drones/MoveToDroneBay',
     'UI/Corporations/CorporationWindow/Members/CorpMember',
     'UI/Inventory/ItemActions/CreateContract',
     'UI/Corporations/Common/AwardCorpMemberDecoration',
     'UI/EVEMail/SendPilotEVEMail',
     'UI/PeopleAndPlaces/RemoveFromAddressbook',
     'UI/PeopleAndPlaces/AddToAddressbook',
     'UI/Fleet/FormFleetWith',
     'UI/Commands/CapturePortrait',
     'UI/Inventory/ItemActions/LaunchShip',
     'UI/Inventory/ItemActions/LaunchShipFromBay',
     'UI/Inventory/ItemActions/GetRepairQuote']
    return multiFunctions
