#Embedded file name: spacecomponents/common/components\turboshield.py
TURBO_SHIELD_STATE_ACTIVE = 0
TURBO_SHIELD_STATE_INVULNERABLE = 1
TURBO_SHIELD_STATE_RESISTIVE = 2
TURBO_SHIELD_STATE_DEPLETED = 3
