#Embedded file name: eve/client/script/ui/inflight\overviewConst.py
HTML_ENTITIES = '&gt;|&lt;|&amp;|&GT;|&LT;|&AMP;'
HTML_ENTITY_REPLACEMENTS = {'&gt;': u'>',
 '&lt;': u'<',
 '&amp;': u'&',
 '&GT;': u'>',
 '&LT;': u'<',
 '&AMP;': u'&'}
COLUMN_VELOCITY = 'VELOCITY'
COLUMN_RADIALVELOCITY = 'RADIALVELOCITY'
COLUMN_ANGULARVELOCITY = 'ANGULARVELOCITY'
COLUMN_TRANSVERSALVELOCITY = 'TRANSVERSALVELOCITY'
COLUMN_DISTANCE = 'DISTANCE'
COLUMN_SIZE = 'SIZE'
COLUMN_MILITIA = 'MILITIA'
COLUMN_FACTION = 'FACTION'
COLUMN_CORPORATION = 'CORPORATION'
COLUMN_TAG = 'TAG'
COLUMN_TYPE = 'TYPE'
COLUMN_NAME = 'NAME'
COLUMN_ICON = 'ICON'
COLUMN_ALLIANCE = 'ALLIANCE'
COLUMNFADESIZE = 20
COLUMNMARGIN = 4
COLUMNMINSIZE = 24
COLUMNMINDEFAULTSIZE = 80
FIXEDCOLUMNS = {COLUMN_ICON: 22}
ALLCOLUMNS = [COLUMN_VELOCITY,
 COLUMN_RADIALVELOCITY,
 COLUMN_ANGULARVELOCITY,
 COLUMN_TRANSVERSALVELOCITY,
 COLUMN_DISTANCE,
 COLUMN_SIZE,
 COLUMN_MILITIA,
 COLUMN_FACTION,
 COLUMN_CORPORATION,
 COLUMN_TAG,
 COLUMN_TYPE,
 COLUMN_NAME,
 COLUMN_ICON,
 COLUMN_ALLIANCE]
RIGHTALIGNEDCOLUMNS = [COLUMN_DISTANCE,
 COLUMN_SIZE,
 COLUMN_VELOCITY,
 COLUMN_RADIALVELOCITY,
 COLUMN_ANGULARVELOCITY,
 COLUMN_TRANSVERSALVELOCITY]
CURVE_HOSTILE = 2
CURVE_ATTACKING = 3
INVISIBLE_SPACEOBJECT_ICON = 'res:/UI/Texture/Icons/38_16_241.png'
FMT_M = None
FMT_KM = None
FMT_AU = None
FMT_VELOCITY = None
global FMT_AU ## Warning: Unused global
global FMT_M ## Warning: Unused global
global FMT_KM ## Warning: Unused global
global FMT_VELOCITY ## Warning: Unused global
