#Embedded file name: actionProperties.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.script.entities.AI.aimingProcs import AITarget
from carbon.common.script.entities.AI.perceptionProcs import AICandidate
from carbon.common.script.entities.AI.perceptionProcs import AIConfidence
from carbon.common.script.entities.AI.perceptionProcs import AIStimType
from carbon.common.script.entities.AI.perceptionProcs import AISubject
from carbon.common.script.entities.entityProcs import LocatorList
from carbon.common.script.entities.entityProcs import MotionState
from carbon.common.script.entities.entityProcs import TargetTypeList
from carbon.common.script.zaction.AnimationProcs import ControlParameters
