#Embedded file name: agentDialogueUtil.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.ui.station.agents.agentDialogueUtil import BuildObjectiveHTML
from eve.client.script.ui.station.agents.agentDialogueUtil import CHECK_ICON
from eve.client.script.ui.station.agents.agentDialogueUtil import CIRCLE_ICON
from eve.client.script.ui.station.agents.agentDialogueUtil import CROSS_ICON
from eve.client.script.ui.station.agents.agentDialogueUtil import GetAgentLocationHeader
from eve.client.script.ui.station.agents.agentDialogueUtil import HIGH_SEC_COLOR
from eve.client.script.ui.station.agents.agentDialogueUtil import IconWrap
from eve.client.script.ui.station.agents.agentDialogueUtil import LOW_SEC_COLOR
from eve.client.script.ui.station.agents.agentDialogueUtil import LocationWrapper
from eve.client.script.ui.station.agents.agentDialogueUtil import MEDIUM_HIGH_SEC_COLOR
from eve.client.script.ui.station.agents.agentDialogueUtil import MEDIUM_SEC_COLOR
from eve.client.script.ui.station.agents.agentDialogueUtil import OwnerWrap
from eve.client.script.ui.station.agents.agentDialogueUtil import ProcessDungeonData
from eve.client.script.ui.station.agents.agentDialogueUtil import ProcessObjectiveEntry
from eve.client.script.ui.station.agents.agentDialogueUtil import ProcessTypeAndQuantity
from eve.client.script.ui.station.agents.agentDialogueUtil import SECURITY_COLORS
