#Embedded file name: allianceObject.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.ui.services.alliances.all_cso_base import BaseAllianceObject as base
from eve.client.script.ui.services.alliances.all_cso_alliance import AllianceO as alliance
from eve.client.script.ui.services.alliances.all_cso_applications import AllianceApplicationsO as applications
from eve.client.script.ui.services.alliances.all_cso_members import AllianceMembersO as members
from eve.client.script.ui.services.alliances.all_cso_relationships import AllianceRelationshipsO as relationships
