#Embedded file name: audioConst.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbonui.audioConst import BTNCLICK_DEFAULT
from eve.client.script.ui.eveAudioConst import BTNCLICK_DEFAULT
