#Embedded file name: audio.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.lib.audio import *
from carbon.common.script.entities.audioEmitter import AudioEmitterComponent
from carbon.common.script.entities.audioEmitter import EMITTER_GROUP_NAME
from carbon.common.script.entities.audioEmitter import INITIAL_EVENT_NAME
from carbon.common.script.entities.audioEmitter import INITIAL_SOUND_ID
