#Embedded file name: bookmarkUtil.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.util.bookmarkUtil import BOOKMARK_RIGHTCLICK_GROUPING_THRESHOLD
from eve.client.script.util.bookmarkUtil import GetBookmarkMenuForSystem
from eve.client.script.util.bookmarkUtil import GetFolderedMenu
from eve.client.script.util.bookmarkUtil import GetMenuForBookmarks
