#Embedded file name: bountyUtil.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.common.script.util.bountyUtil import CacheBounties
from eve.common.script.util.bountyUtil import GetMinimumBountyAmount
