#Embedded file name: bracketUtils.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.ui.inflight.bracketsAndTargets.bracketVarious import FixLines
from eve.client.script.ui.inflight.bracketsAndTargets.bracketVarious import GROUPS_WITH_LOOTRIGHTS
from eve.client.script.ui.inflight.bracketsAndTargets.bracketVarious import GetEntityStateString
from eve.client.script.ui.inflight.bracketsAndTargets.bracketVarious import GetIconColor
from eve.client.script.ui.inflight.bracketsAndTargets.bracketVarious import IsAbandonedContainer
from eve.client.script.ui.inflight.bracketsAndTargets.bracketVarious import IsForbiddenContainer
from eve.client.script.ui.inflight.bracketsAndTargets.bracketVarious import LABELMARGIN
from eve.client.script.ui.inflight.bracketsAndTargets.bracketVarious import SHOWLABELS_ALWAYS
from eve.client.script.ui.inflight.bracketsAndTargets.bracketVarious import SHOWLABELS_NEVER
from eve.client.script.ui.inflight.bracketsAndTargets.bracketVarious import SHOWLABELS_ONMOUSEENTER
from eve.client.script.ui.inflight.bracketsAndTargets.bracketVarious import TARGETTING_UI_UPDATE_RATE
from eve.client.script.ui.inflight.bracketsAndTargets.bracketVarious import TargetingHairlines
from eve.client.script.ui.inflight.bracketsAndTargets.bracketVarious import entityStateStrings
