#Embedded file name: bracket.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.ui.inflight.bracket import LABELMARGIN
from eve.client.script.ui.inflight.bracket import SHOWLABELS_ALWAYS
from eve.client.script.ui.inflight.bracket import SHOWLABELS_NEVER
from eve.client.script.ui.inflight.bracket import SHOWLABELS_ONMOUSEENTER
from eve.client.script.ui.inflight.bracket import TARGETTING_UI_UPDATE_RATE
