#Embedded file name: browserutil.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.ui.control.browser.browserutil import DefaultHomepage
from eve.client.script.ui.control.browser.browserutil import GetFixedURL
from eve.client.script.ui.control.browser.browserutil import SanitizedDestinationID
from eve.client.script.ui.control.browser.browserutil import SanitizedItemID
from eve.client.script.ui.control.browser.browserutil import SanitizedSolarsystemID
from eve.client.script.ui.control.browser.browserutil import SanitizedTypeID
