#Embedded file name: browser.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbonui.control.browser.browserPane import CoreBrowserPane
from carbonui.control.browser.browserSession import CoreBrowserSession
from eve.client.script.ui.control.browser.browserSession import EveBrowserSession as BrowserSession
from eve.client.script.ui.control.browser.eveBrowserPane import BrowserPane
