#Embedded file name: cameraUtils.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbonui.util.cameraUtils import CalcDesiredPlayerHeading
from carbonui.util.cameraUtils import GetAngleFromEntityToCamera
from carbonui.util.cameraUtils import GetAngleFromEntityToYaw
from carbonui.util.cameraUtils import GetEntityYaw
from carbonui.util.cameraUtils import ReverseCameraYaw
