#Embedded file name: ccUtil.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.ui.login.charcreation.bloodlineSelector import BloodlineSelector
from eve.client.script.ui.login.charcreation.ccUtil import GenderIDToPaperDollGender
from eve.client.script.ui.login.charcreation.ccUtil import HasUserDefinedSpecularity
from eve.client.script.ui.login.charcreation.ccUtil import HasUserDefinedWeight
from eve.client.script.ui.login.charcreation.ccUtil import LoadFromYaml
from eve.client.script.ui.login.charcreation.ccUtil import PaperDollGenderToGenderID
from eve.client.script.ui.login.charcreation.ccUtil import SetupLighting
from eve.client.script.ui.login.charcreation.ccUtil import SupportsHigherShaderModel
