#Embedded file name: chatconst.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.ui.shared.comtool.constants import CHANNEL_CUSTOM
from eve.client.script.ui.shared.comtool.constants import CHANNEL_FLEET
