#Embedded file name: corebrowserutil.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbonui.control.browser.browserutil import CrashedBrowserViewHost
from carbonui.control.browser.browserutil import Css
from carbonui.control.browser.browserutil import DefaultCachePath
from carbonui.control.browser.browserutil import DefaultHomepage
from carbonui.control.browser.browserutil import DirUp
from carbonui.control.browser.browserutil import GetErrorString
from carbonui.control.browser.browserutil import GetStringFromURL
from carbonui.control.browser.browserutil import LoadErrors
from carbonui.control.browser.browserutil import NewBrowserForm
from carbonui.control.browser.browserutil import NextPowerOfTwo
from carbonui.control.browser.browserutil import ParseURL
from carbonui.control.browser.cookieManager import CookieManager
