#Embedded file name: corputil.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.ui.services.corporation.corp_util import CanEditBase
from eve.client.script.ui.services.corporation.corp_util import CanEditRole
from eve.client.script.ui.services.corporation.corp_util import GROUP_DIVISIONAL_ACCOUNTING_ROLES
from eve.client.script.ui.services.corporation.corp_util import GROUP_DIVISIONAL_CONTAINER_ROLES_AT_BASE
from eve.client.script.ui.services.corporation.corp_util import GROUP_DIVISIONAL_CONTAINER_ROLES_AT_HQ
from eve.client.script.ui.services.corporation.corp_util import GROUP_DIVISIONAL_CONTAINER_ROLES_AT_OTHER
from eve.client.script.ui.services.corporation.corp_util import GROUP_DIVISIONAL_HANGAR_ROLES_AT_BASE
from eve.client.script.ui.services.corporation.corp_util import GROUP_DIVISIONAL_HANGAR_ROLES_AT_HQ
from eve.client.script.ui.services.corporation.corp_util import GROUP_DIVISIONAL_HANGAR_ROLES_AT_OTHER
from eve.client.script.ui.services.corporation.corp_util import GROUP_GENERAL_ROLES
from eve.client.script.ui.services.corporation.corp_util import RECRUITMENT_GROUP_PRIMARY_LANGUAGE
from eve.client.script.ui.services.corporation.corp_util import VIEW_GRANTABLE_ROLES
from eve.client.script.ui.services.corporation.corp_util import VIEW_ROLES
from eve.client.script.ui.services.corporation.corp_util import VIEW_TITLES
