#Embedded file name: corpObject.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.ui.services.corporation.bco_base import BaseCorpObject as base
from eve.client.script.ui.services.corporation.bco_alliance import CorpAllianceO as alliance
from eve.client.script.ui.services.corporation.bco_applications import ApplicationsO as applications
from eve.client.script.ui.services.corporation.bco_corporations import CorporationsO as corporations
from eve.client.script.ui.services.corporation.bco_itemLocking import ItemLockingO as itemLocking
from eve.client.script.ui.services.corporation.bco_locations import LocationsO as locations
from eve.client.script.ui.services.corporation.bco_members import CorporationMembersO as members
from eve.client.script.ui.services.corporation.bco_recruitment import CorporationRecruitmentO as recruitment
from eve.client.script.ui.services.corporation.bco_sanctionedActions import SanctionedActionsO as sanctionedActions
from eve.client.script.ui.services.corporation.bco_shares import SharesO as shares
from eve.client.script.ui.services.corporation.bco_titles import TitlesO as titles
from eve.client.script.ui.services.corporation.bco_voting import VotingO as voting
from eve.client.script.ui.services.corporation.bco_wars import WarsO as wars
