#Embedded file name: cqscreen.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.ui.station.captainsquarters.mainScreen import CorpFinderScreen
from eve.client.script.ui.station.captainsquarters.mainScreen import MainScreen
from eve.client.script.ui.station.captainsquarters.mainScreen import PIScreen
from eve.client.script.ui.station.captainsquarters.mainScreen import ScreenNewsTicker
