#Embedded file name: dbg.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.client.script.util.debug import ImportHack
from carbon.client.script.util.debug import Prettify
from carbon.client.script.util.debug import Profile
from carbon.client.script.util.debug import Profiled
from carbon.client.script.util.debug import Trace
from carbon.client.script.util.debug import TraceAll
from carbon.client.script.util.debug import TraceLocals
from carbon.client.script.util.debug import WithLogStdout
from eve.client.script.util.eveDebug import GetCharacterName
