#Embedded file name: defaultRangeUtils.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.ui.util.defaultRangeUtils import FetchRangeSetting
from eve.client.script.ui.util.defaultRangeUtils import UpdateRangeSetting
