#Embedded file name: defaultsetting.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbonui.util.defaultsetting import char
from carbonui.util.defaultsetting import public
from carbonui.util.defaultsetting import user
