#Embedded file name: device.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.client.script.graphics.device import SetCharMipLevelSkipCount
from carbon.client.script.graphics.device import SetEnvMipLevelSkipCount
