#Embedded file name: entity.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.client.script.entities.selectionClient import SelectionClientComponent
from carbon.client.script.entities.simpleTestClient import SimpleTestClientComponent
