#Embedded file name: eveCfg.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.common.script.sys.eveCfg import Constellation
from eve.common.script.sys.eveCfg import InvCategory
from eve.common.script.sys.eveCfg import InvGroup
from eve.common.script.sys.eveCfg import InvItem2
from eve.common.script.sys.eveCfg import InvType
from eve.common.script.sys.eveCfg import OverviewDefault
from eve.common.script.sys.eveCfg import Region
from eve.common.script.sys.eveCfg import SolarSystem
from eve.common.script.sys.eveCfg import Standings
