#Embedded file name: eveparser.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbonui.control.editutils.parser import ErrorMsg
from carbonui.control.editutils.parser import Parser as Html
from carbonui.control.editutils.parser import HtmlAutoClose
from carbonui.control.editutils.parser import HtmlColors
from carbonui.control.editutils.parser import HtmlIgnoredTags
from carbonui.control.editutils.parser import HtmlOptionalClose
from carbonui.control.editutils.parser import HtmlSupportedTags
from carbonui.control.editutils.parserbase import ParserBaseCore
from eve.client.script.ui.control.eveEdit_Parser import ParserBase
