#Embedded file name: GameWorld.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.lib.GameWorld import *
from carbon.common.script.world.GameWorldService import GameWorldService
