#Embedded file name: html.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbonui.control.editutils.css import css as Css
from carbonui.control.editutils.parser import ALIGNBASELINE
from carbonui.control.editutils.parser import ALIGNBOTTOM
from carbonui.control.editutils.parser import ALIGNMIDDLE
from carbonui.control.editutils.parser import ALIGNSUB
from carbonui.control.editutils.parser import ALIGNSUPER
from carbonui.control.editutils.parser import ALIGNTOP
from carbonui.control.editutils.parser import BG_FIXED
from carbonui.control.editutils.parser import BG_SCROLL
from carbonui.control.editutils.parser import BG_TILED
