#Embedded file name: httpAuth.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.script.net.httpAuth import AllOf
from carbon.common.script.net.httpAuth import AnyOf
from carbon.common.script.net.httpAuth import AuthController
from carbon.common.script.net.httpAuth import CheckAuth
from carbon.common.script.net.httpAuth import CheckCredentials
from carbon.common.script.net.httpAuth import CreateSession
from carbon.common.script.net.httpAuth import EndSession
from carbon.common.script.net.httpAuth import MemberOf
from carbon.common.script.net.httpAuth import NameIs
from carbon.common.script.net.httpAuth import Require
