#Embedded file name: httpJinja.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.script.net.httpJinja import CherryPyApp
from carbon.common.script.net.httpJinja import TemplateRender
