#Embedded file name: http.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.script.net.http import AddHeader
from carbon.common.script.net.http import ESPUrl
from carbon.common.script.net.http import Escape
from carbon.common.script.net.http import GetCookie
from carbon.common.script.net.http import GetSessionData
from carbon.common.script.net.http import Host
from carbon.common.script.net.http import Referer
from carbon.common.script.net.http import RemoteAddress
from carbon.common.script.net.http import SPSession
from carbon.common.script.net.http import SaveString
from carbon.common.script.net.http import Session
from carbon.common.script.net.http import SetCookie
from carbon.common.script.net.http import SetSessionData
