#Embedded file name: incursion.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.ui.shared.incursionJournal import IncursionTab
from eve.client.script.ui.shared.incursionJournal import BigReportLabel as ReportLabel
from eve.client.script.ui.shared.incursionJournal import ReportNumber
