#Embedded file name: invCache.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.environment.invCache import inv5MinCacheContainer
from eve.client.script.environment.invCache import invCacheContainer
