#Embedded file name: inventoryFlagsCommon.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.common.script.util.inventoryFlagsCommon import GetBaysToCheck
from eve.common.script.util.inventoryFlagsCommon import GetNameForFlag
from eve.common.script.util.inventoryFlagsCommon import ShouldAllowAdd
from eve.common.script.util.inventoryFlagsCommon import autoConsumeCategories
from eve.common.script.util.inventoryFlagsCommon import autoConsumeGroups
from eve.common.script.util.inventoryFlagsCommon import autoConsumeTypes
from eve.common.script.util.inventoryFlagsCommon import inventoryFlagData
