#Embedded file name: itools.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.devtools.script.itools import itertree
from eve.devtools.script.itools import listify
from eve.devtools.script.itools import relpath
from eve.devtools.script.itools import walktree
