#Embedded file name: lightfx.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.ui.extras.lightfxsvc import BackgroundLightEffect
from eve.client.script.ui.extras.lightfxsvc import BlinkingLedEffect
from eve.client.script.ui.extras.lightfxsvc import BreathingLedEffect
from eve.client.script.ui.extras.lightfxsvc import FadeOutEffect as FadeOut
from eve.client.script.ui.extras.lightfxsvc import LedEffect
