#Embedded file name: loadRequest.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.lib.loadRequest import *
from carbon.client.script.graphics.graphicLoaderRequest import GraphicLoaderRequest
