#Embedded file name: login.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.ui.login.loginII import GetServerIP
from eve.client.script.ui.login.loginII import GetServerInfo
from eve.client.script.ui.login.loginII import GetServerName
from eve.client.script.ui.login.loginII import servers
