#Embedded file name: maputils.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.ui.shared.maps.maputils import GetDistance
from eve.client.script.ui.shared.maps.maputils import GetHintsOnSolarsystemBrackets
from eve.client.script.ui.shared.maps.maputils import GetMyPos
from eve.client.script.ui.shared.maps.maputils import GetNameFromMapCache
from eve.client.script.ui.shared.maps.maputils import GetValidSolarsystemGroups
from eve.client.script.ui.shared.maps.maputils import GetVisibleSolarsystemBrackets
