#Embedded file name: mathUtil.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.script.util.mathUtil import DEG_2_RAD
from carbon.common.script.util.mathUtil import DegToRad
from carbon.common.script.util.mathUtil import Lerp
from carbon.common.script.util.mathUtil import LerpByTime
from carbon.common.script.util.mathUtil import LerpList
from carbon.common.script.util.mathUtil import LerpTupleFour
from carbon.common.script.util.mathUtil import LerpTupleThree
from carbon.common.script.util.mathUtil import LerpVector
from carbon.common.script.util.mathUtil import LtoI
from carbon.common.script.util.mathUtil import RAD_2_DEG
from carbon.common.script.util.mathUtil import RadToDeg
from carbon.common.script.util.mathUtil import RayToPlaneIntersection
