#Embedded file name: miscUtil.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.script.util.miscUtil import CommonResourceExists
from carbon.common.script.util.miscUtil import Flatten
from carbon.common.script.util.miscUtil import GetCommonResource
from carbon.common.script.util.miscUtil import GetCommonResourcePath
from carbon.common.script.util.miscUtil import IsInstance_BlueType
