#Embedded file name: movement.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.lib.movement import *
from carbon.common.script.movement.movementService import CommonMovementComponent
from carbon.common.script.movement.movementService import MovementService as movementService
from carbon.common.script.movement.movementStates import MovementStates
from carbon.client.script.movement.inputMap import InputMap
from eve.client.script.movement.eveInputMap import EveInputMap
from eve.client.script.movement.eveMovementClient import MovementClientComponent
