#Embedded file name: naiveXML.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.client.script.util.naiveXML import Extract
from carbon.client.script.util.naiveXML import Field
