#Embedded file name: nodemanager.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.environment.nodemanager import FindNode
from eve.client.script.environment.nodemanager import FindNodes
