#Embedded file name: numerical.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.script.util.numerical import FrameClock
from carbon.common.script.util.numerical import KalmanFilter
from carbon.common.script.util.numerical import KalmanFilterSS
