#Embedded file name: objectCaching.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.script.net.objectCaching import CacheOK
from carbon.common.script.net.objectCaching import CachedMethodCallResult
from carbon.common.script.net.objectCaching import CachedObject
