#Embedded file name: paperDollSculpting.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.paperDoll.paperDollSculpting import PaperDollSculpting as Sculpting
