#Embedded file name: PaperdollSculptingGhost.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.paperDoll.PaperdollSculptingGhost import PaperdollSculptingGhost
