#Embedded file name: planetSurfaceCommon.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.common.script.planet.planetSurfaceCommon import GetMaximumPinInstances
from eve.common.script.planet.planetSurfaceCommon import GetOrbitalConstructionPrerequisites
from eve.common.script.planet.planetSurfaceCommon import GetSurfaceConstructionPrerequisites
from eve.common.script.planet.planetSurfaceCommon import GetValidPlanetTypesForPinType
