#Embedded file name: pos.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.common.script.mgt.posConst import DISPLAY_NAMES
from eve.common.script.mgt.posConst import Entity2DB
from eve.common.script.mgt.posConst import GetEntityStatesForDBState
from eve.common.script.mgt.posConst import GetJumpFuelConsumption
from eve.common.script.mgt.posConst import IsStructureAnchored
from eve.common.script.mgt.posConst import ONLINE_STABLE_STATES
from eve.common.script.mgt.posConst import STRUCTURE_ANCHORED
from eve.common.script.mgt.posConst import STRUCTURE_ARMOR_REINFORCE
from eve.common.script.mgt.posConst import STRUCTURE_INVULNERABLE
from eve.common.script.mgt.posConst import STRUCTURE_ONLINE
from eve.common.script.mgt.posConst import STRUCTURE_ONLINING
from eve.common.script.mgt.posConst import STRUCTURE_OPERATING
from eve.common.script.mgt.posConst import STRUCTURE_REINFORCED
from eve.common.script.mgt.posConst import STRUCTURE_SHIELD_REINFORCE
from eve.common.script.mgt.posConst import STRUCTURE_UNANCHORED
from eve.common.script.mgt.posConst import STRUCTURE_VULNERABLE
