#Embedded file name: prepassConversion.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.client.script.util.prepassConversion import AddPrepassAreasToDynamic
from carbon.client.script.util.prepassConversion import AddPrepassAreasToStatic
