#Embedded file name: profiling.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.script.util.profiling import CalcMemoryUsage
from carbon.common.script.util.profiling import CheckSM
from carbon.common.script.util.profiling import RefTracker
from eve.client.script.util.profiling import FPSProfiler
from eve.client.script.util.profiling import Get
from eve.client.script.util.profiling import Start
from eve.client.script.util.profiling import TotalProfiler
