#Embedded file name: safeThread.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.script.util.safeThread import DoMethodLater
from carbon.common.script.util.safeThread import SafeThread
from carbon.common.script.util.safeThread import SleepAndCallAtTime
