#Embedded file name: sceneManager.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.parklife.sceneManagerConsts import SCENE_TYPE_CHARACTER_CREATION
from eve.client.script.parklife.sceneManagerConsts import SCENE_TYPE_INTERIOR
from eve.client.script.parklife.sceneManagerConsts import SCENE_TYPE_SPACE
