#Embedded file name: searchUtil.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.ui.util.searchUtil import IsMatch
from eve.client.script.ui.util.searchUtil import QuickSearch
from eve.client.script.ui.util.searchUtil import Search
from eve.client.script.ui.util.searchUtil import SearchCharacters
