#Embedded file name: shipSafetyButton.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.ui.inflight.shipSafetyButton import LightEmittingDiode
from eve.client.script.ui.inflight.shipSafetyButton import SafetyButton
from eve.client.script.ui.inflight.shipSafetyButton import SafetyLevelSelector
from eve.client.script.ui.inflight.shipSafetyButton import SecurityButton
