#Embedded file name: storeConst.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.common.script.mgt.storeConst import GOODTYPE_CREDITS
from eve.common.script.mgt.storeConst import GOODTYPE_EVETYPEID
from eve.common.script.mgt.storeConst import NPC_STORE_HOLDING_CORP
from eve.common.script.mgt.storeConst import PRODUCT_DUST
from eve.common.script.mgt.storeConst import PRODUCT_EVE
