#Embedded file name: sys_extra.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.common.script.sys.strangeStrings import A
from eve.common.script.sys.strangeStrings import AgentString
from eve.common.script.sys.strangeStrings import AgentUnicode
