#Embedded file name: timerstuff.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.script.util.timerstuff import ClockThis
from carbon.common.script.util.timerstuff import ClockThisWithoutTheStars
from carbon.common.script.util.timerstuff import SimpleTimingContext
from carbon.common.script.util.timerstuff import TimeThis
from carbon.common.script.util.timerstuff import TracebackTimingContext
from carbon.common.script.util.timerstuff import TracebackTimingFunction
