#Embedded file name: uipointer.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.client.script.ui.shared.spaceObjectUiPointer import FloatingBox
from eve.client.script.ui.shared.spaceObjectUiPointer import SpaceObjectTypeUiPointer
from eve.client.script.ui.shared.spaceObjectUiPointer import UiPointerContainer
