#Embedded file name: uiprimitives.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbonui.primitives.area import Area
from carbonui.primitives.backgroundList import BackgroundList
from carbonui.primitives.base import Base
from carbonui.primitives.boundingboxbracket import BoundingBoxBracket
from carbonui.primitives.bracket import Bracket
from carbonui.primitives.childrenlist import PyChildrenList as UIChildrenList
from carbonui.primitives.container import Container
from carbonui.primitives.desktop import UIRoot
from carbonui.primitives.dragdrop import DragDropObject
from carbonui.primitives.fill import Fill
from carbonui.primitives.fill import Fill as FillCore
from carbonui.primitives.frame import Frame as FrameCore
from carbonui.primitives.line import Line
from carbonui.primitives.sprite import Sprite
from carbonui.primitives.sprite import TexturedBase
from carbonui.primitives.sprite import VideoSprite
from carbonui.primitives.sprite import VisibleBase
from carbonui.primitives.transform import Transform
from carbonui.primitives.vectorlinetrace import VectorLineTrace
