#Embedded file name: warUtil.py
"""This is an autogenerated file to mimic the nasty namespace."""
from eve.common.script.util.warUtil import CreateWarFromRow
from eve.common.script.util.warUtil import GetAddRemoveFromChange
from eve.common.script.util.warUtil import GetAllyCostToConcord
from eve.common.script.util.warUtil import HandleWarChange
from eve.common.script.util.warUtil import ProcessAllyJoinNotifications
from eve.common.script.util.warUtil import War
