#Embedded file name: world.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.lib.world import *
from carbon.common.script.world.enlightenArea import EnlightenArea
from carbon.common.script.world.objectLightOverride import ObjectLightOverride
from carbon.common.script.world.worldSpaceCommon import GetWorldSpace
from carbon.common.script.world.worldSpaceCommon import GetWorldSpaceName
from carbon.common.script.world.worldSpaceCommon import WorldSpace
from carbon.common.script.world.worldSpaceCommonSvc import BaseWorldSpaceService as CoreBaseWorldSpaceService
from carbon.client.script.world.worldSpaceScene import WorldSpaceScene as CoreWorldSpaceScene
from eve.common.script.world.eveBaseWorldSpaceSvc import EveBaseWorldSpaceService as BaseWorldSpaceService
from eve.client.script.world.eveWorldSpaceScene import EveWorldSpaceScene as WorldSpaceScene
