#Embedded file name: zaction.py
"""This is an autogenerated file to mimic the nasty namespace."""
from carbon.common.script.zaction.zactionCommon import ActionComponent
from carbon.common.script.zaction.zactionCommon import AddPropertyForCurrentPythonProc
from carbon.common.script.zaction.zactionCommon import GetPropertyForCurrentPythonProc
from carbon.common.script.zaction.zactionCommon import ProcNameHelper
from carbon.common.script.zaction.zactionCommon import ProcPropertyTypeDef
from carbon.common.script.zaction.zactionCommon import ProcTypeDef
from carbon.common.script.zaction.zactionCommon import zactionCommon
from carbon.common.script.zaction.zactionCommon import zactionCommonBase
