#Embedded file name: eve/client/script/ui/login/charcreation\assetRendererConst.py
import ccConst
from math import pi
pi05 = pi * 0.5
DRESSCODE = {ccConst.eyes: (ccConst.eyebrows,),
 ccConst.eyeshadow: (ccConst.eyebrows,),
 ccConst.eyelashes: (ccConst.eyebrows,),
 ccConst.eyeliner: (ccConst.eyebrows,),
 ccConst.lipstick: (ccConst.eyebrows,),
 ccConst.blush: (ccConst.eyebrows,),
 ccConst.hair: (ccConst.topmiddle, ccConst.eyebrows),
 ccConst.eyebrows: (ccConst.hair,),
 ccConst.bottomouter: (ccConst.topmiddle, ccConst.feet),
 ccConst.topmiddle: (ccConst.bottomouter, ccConst.eyebrows, ccConst.hair),
 ccConst.topouter: (ccConst.bottomouter,
                    ccConst.topmiddle,
                    ccConst.eyebrows,
                    ccConst.hair),
 ccConst.outer: (ccConst.bottomouter,
                 ccConst.topmiddle,
                 ccConst.eyebrows,
                 ccConst.hair),
 ccConst.glasses: (ccConst.topmiddle, ccConst.eyebrows, ccConst.hair),
 ccConst.beard: (ccConst.hair, ccConst.eyebrows, ccConst.topmiddle),
 ccConst.feet: (ccConst.bottomouter,),
 ccConst.p_earslow: (ccConst.eyebrows, ccConst.hair),
 ccConst.p_earshigh: (ccConst.eyebrows, ccConst.hair),
 ccConst.p_nose: (ccConst.eyebrows, ccConst.hair),
 ccConst.p_nostril: (ccConst.eyebrows, ccConst.hair),
 ccConst.p_brow: (ccConst.eyebrows, ccConst.hair),
 ccConst.p_lips: (ccConst.eyebrows,),
 ccConst.t_head: (ccConst.eyebrows, ccConst.hair),
 ccConst.s_head: (ccConst.eyebrows, ccConst.hair),
 ccConst.t_armleft: (ccConst.eyebrows,
                     ccConst.hair,
                     ccConst.topmiddle,
                     ccConst.bottomouter),
 ccConst.t_armright: (ccConst.eyebrows,
                      ccConst.hair,
                      ccConst.topmiddle,
                      ccConst.bottomouter)}
SETUP = {ccConst.eyes: ('fj_eyeballRight', (0.15,
                 0,
                 0,
                 pi05 + 0.15,
                 pi05 - 0.07), None),
 ccConst.lipstick: ('fj_lip_lower_center', (0.2,
                     0,
                     0,
                     pi05 + 0.4,
                     pi05 + 0.05), None),
 ccConst.eyeshadow: ('fj_eyeballRight', (0.2,
                      0,
                      0,
                      pi05 + 0.3,
                      pi05 + 0.05), None),
 ccConst.eyelashes: ('fj_eyeballRight', (0.15,
                      0,
                      0,
                      pi05 + 0.3,
                      pi05 + 0.05), None),
 ccConst.eyeliner: ('fj_eyeballRight', (0.15,
                     0,
                     0,
                     pi05 + 0.3,
                     pi05 + 0.05), None),
 ccConst.eyebrows: ('fj_eyeballRight', (0.2,
                     0,
                     0,
                     pi05 + 0.3,
                     pi05 + 0.05), None),
 ccConst.hair: ('Head_End', (1.1,
                 -0.14,
                 0,
                 pi05 - 0.3,
                 pi05 + 0.3), None),
 ccConst.beard: ('fj_lip_lower_center', (0.4,
                  0,
                  -0.015,
                  pi05 + 0.1,
                  pi05 + 0.3), None),
 ccConst.blush: ('Head', (0.6,
                  0,
                  0,
                  pi05 - 0.3,
                  pi05 + 0.3), 'SoftCenterRimSides'),
 ccConst.glasses: ('Head', (0.65,
                    0,
                    -0.02,
                    pi05 - 0.2,
                    pi05 + 0.3), None),
 ccConst.topmiddle: ('Spine3', (3.0,
                      0,
                      0,
                      pi05 - 0.3,
                      pi05 + 0.3), None),
 ccConst.topouter: ('Spine3', (3.0,
                     0,
                     0,
                     pi05 - 0.3,
                     pi05 + 0.3), None),
 ccConst.outer: ('Spine1', (3.5,
                  0,
                  0,
                  pi05 - 0.3,
                  pi05 + 0.3), None),
 ccConst.bottomouter: ('LeftLeg', (3.5,
                        0,
                        0,
                        pi05 + 0.5,
                        pi05 + 0.3), None),
 ccConst.bottommiddle: ('LeftLeg', (3.5,
                         0,
                         0,
                         pi05 + 0.5,
                         pi05 + 0.3), None),
 ccConst.feet: ('LeftFoot', (1.5,
                 0,
                 0,
                 pi05 + 0.5,
                 pi05 + 0.3), 'shoes'),
 ccConst.p_earslow: ('fj_ear_wiggle', (0.4,
                      -0.025,
                      0,
                      pi + 0.1,
                      pi05), None),
 ccConst.p_earshigh: ('fj_ear_wiggle', (0.27,
                       -0.005,
                       0,
                       pi + 0.2,
                       pi05), None),
 ccConst.p_nose: ('fj_nose_left', (0.25,
                   0.02,
                   -0.01,
                   pi05 - 0.2,
                   pi05 + 0.3), None),
 ccConst.p_nostril: ('fj_nose_left', (0.2,
                      -0.01,
                      -0.01,
                      pi05 + 0.35,
                      pi05 + 0.2), None),
 ccConst.p_brow: ('fj_eyeballRight', (0.18,
                   0.005,
                   -0.005,
                   pi05 + 0.15,
                   pi05 - 0.07), None),
 ccConst.p_lips: ('fj_lip_lower_center', (0.2,
                   0,
                   0,
                   pi05 + 0.4,
                   pi05 + 0.05), None),
 ccConst.p_chin: ('fj_lip_lower_center', (0.2,
                   0,
                   0,
                   pi05 + 0.4,
                   pi05 + 0.05), None),
 ccConst.t_head: ('Head_End', (0.8,
                   -0.14,
                   0,
                   pi05 - 0.1,
                   pi05), None),
 ccConst.s_head: ('Head_End', (0.65,
                   -0.14,
                   0,
                   pi05 - 0.05,
                   pi05), None),
 ccConst.t_armright: ('Head', (1.4,
                       -0.35,
                       -0.15,
                       pi * 4.5 / 6 + 0.5,
                       pi05), None),
 ccConst.t_armleft: ('Head', (1.4,
                      -0.35,
                      0.15,
                      pi * 1 / 6 + 0.5,
                      pi05), None),
 ccConst.pr_armright: ('Head', (1.8,
                        -0.32,
                        -0.05,
                        pi * 4.55 / 6 + 0.5,
                        pi05), None),
 ccConst.pr_armleft: ('Head', (1.8,
                       -0.32,
                       0.05,
                       pi * 1 / 6 + 0.5,
                       pi05), None),
 (ccConst.t_armright, ccConst.GENDERID_MALE): ('Head', (1.4,
                                                -0.3,
                                                -0.1,
                                                pi * 4.5 / 6,
                                                pi / 2), None),
 (ccConst.t_armleft, ccConst.GENDERID_MALE): ('Head', (1.4,
                                               -0.3,
                                               0.15,
                                               pi * 1 / 6,
                                               pi / 2), None),
 (ccConst.pr_armright, ccConst.GENDERID_MALE): ('Head', (1.4,
                                                 -0.3,
                                                 -0.1,
                                                 pi * 4.5 / 6,
                                                 pi / 2), None),
 (ccConst.pr_armleft, ccConst.GENDERID_MALE): ('Head', (1.4,
                                                -0.3,
                                                0.15,
                                                pi * 1 / 6,
                                                pi / 2), None),
 (ccConst.t_armright, ccConst.GENDERID_FEMALE): ('Head', (1.4,
                                                  -0.35,
                                                  -0.15,
                                                  pi * 4.5 / 6 + 0.5,
                                                  pi05), None),
 (ccConst.t_armleft, ccConst.GENDERID_FEMALE): ('Head', (1.8,
                                                 -0.32,
                                                 0.05,
                                                 pi * 1 / 6 + 0.5,
                                                 pi05), None),
 (ccConst.pr_armright, ccConst.GENDERID_FEMALE): ('Head', (1.4,
                                                   -0.35,
                                                   -0.15,
                                                   pi * 4.5 / 6 + 0.5,
                                                   pi05), None),
 (ccConst.pr_armleft, ccConst.GENDERID_FEMALE): ('Head', (1.8,
                                                  -0.32,
                                                  0.05,
                                                  pi * 1 / 6 + 0.5,
                                                  pi05), None)}
FEMALE_EYEBROWS_ID = 172
MALE_EYEBROWS_ID = 107
FEMALE_TOPMIDDLE_ID = 3540
MALE_TOPMIDDLE_ID = 3594
FEMALE_TOPMIDDLE_TANK_ID = 3482
MALE_TOPMIDDLE_TANK_ID = 3590
FEMALE_BOTTOMOUTER_ID = 14894
MALE_BOTTOMOUTER_ID = 14970
FEMALE_HAIR_ID = 421
MALE_HAIR_ID = 296
FEMALE_BOOTS_ID = 8651
MALE_BOOTS_ID = 1068
DRESSCODE_CATEGORIES = (ccConst.eyebrows,
 ccConst.topmiddle,
 ccConst.feet,
 ccConst.bottomouter,
 ccConst.hair)
DRESSCODE_FEMALE_DEFAULT = (FEMALE_EYEBROWS_ID,
 FEMALE_TOPMIDDLE_ID,
 FEMALE_BOTTOMOUTER_ID,
 FEMALE_HAIR_ID,
 FEMALE_BOOTS_ID)
DRESSCODE_MALE_DEFAULT = (MALE_EYEBROWS_ID,
 MALE_TOPMIDDLE_ID,
 MALE_BOTTOMOUTER_ID,
 MALE_HAIR_ID,
 MALE_BOOTS_ID)
DRESSCODE_FEMALE_TTANK = (FEMALE_EYEBROWS_ID,
 FEMALE_TOPMIDDLE_TANK_ID,
 FEMALE_BOTTOMOUTER_ID,
 FEMALE_HAIR_ID,
 FEMALE_BOOTS_ID)
DRESSCODE_MALE_TTANK = (MALE_EYEBROWS_ID,
 MALE_TOPMIDDLE_TANK_ID,
 MALE_BOTTOMOUTER_ID,
 MALE_HAIR_ID,
 MALE_BOOTS_ID)
DRESSCODE_CUSTOM_BY_CATEGORY = {ccConst.t_armleft: (DRESSCODE_FEMALE_TTANK, DRESSCODE_MALE_TTANK),
 ccConst.t_armright: (DRESSCODE_FEMALE_TTANK, DRESSCODE_MALE_TTANK)}
DRESSCODEINDEX = {ccConst.hair: 'shortcut'}
TUCKINDEX = {ccConst.bottomouter: 1}
EXAGGERATE = [(ccConst.blush, ccConst.GENDERID_MALE), (ccConst.eyeliner, ccConst.GENDERID_MALE), (ccConst.lipstick, ccConst.GENDERID_MALE)]
BLOODLINES = ((1, 'caldari_deteis'),
 (2, 'caldari_civire'),
 (11, 'caldari_achura'),
 (7, 'gallente_gallente'),
 (8, 'gallente_intaki'),
 (12, 'gallente_jinmei'),
 (3, 'minmatar_sebiestor'),
 (4, 'minmatar_brutor'),
 (14, 'minmatar_vherokior'),
 (5, 'amarr_amarr'),
 (13, 'amarr_khanid'),
 (6, 'amarr_nikunni'))
SCARGROUPS = {('scars/head/heroscar01', 'v0', ''): 'r_eye',
 ('scars/head/heroscar09', '', ''): 'r_eye',
 ('scars/head/heroscar01', 'v1', ''): 'l_eye',
 ('scars/head/heroscar09', 'v1', ''): 'l_eye',
 ('scars/head/heroscar02', '', ''): 'mouth',
 ('scars/head/heroscar02', 'v1', ''): 'mouth',
 ('scars/head/heroscar05', '', ''): 'forhead',
 ('scars/head/heroscar05', 'v1', ''): 'forhead',
 ('scars/head/heroscar18', '', ''): 'forhead',
 ('scars/head/heroscar11', '', ''): 'forhead',
 ('scars/head/heroscar11', 'v1', ''): 'forhead',
 ('scars/head/heroscar18', 'v1', ''): 'forhead',
 ('scars/head/heroscar08', '', ''): 'chin',
 ('scars/head/heroscar08', 'v1', ''): 'chin',
 ('scars/head/heroscar10', '', ''): 'nose',
 ('scars/head/heroscar10', 'v1', ''): 'nose',
 ('scars/head/heroscar12', '', ''): 'nose',
 ('scars/head/heroscar12', 'v1', ''): 'nose',
 ('scars/head/heroscar06', 'v1', ''): 'r_side',
 ('scars/head/heroscar13', '', ''): 'r_side',
 ('scars/head/heroscar14', '', ''): 'r_side',
 ('scars/head/heroscar15', 'v1', ''): 'r_side',
 ('scars/head/heroscar16', '', ''): 'r_side',
 ('scars/head/heroscar17', '', ''): 'r_side',
 ('scars/head/heroscar03', '', ''): 'r_side',
 ('scars/head/heroscar04', 'v1', ''): 'r_side',
 ('scars/head/heroscar07', 'v1', ''): 'r_side',
 ('scars/head/heroscar03', 'v1', ''): 'l_side',
 ('scars/head/heroscar04', '', ''): 'l_side',
 ('scars/head/heroscar07', '', ''): 'l_side',
 ('scars/head/heroscar06', '', ''): 'l_side',
 ('scars/head/heroscar13', 'v1', ''): 'l_side',
 ('scars/head/heroscar14', 'v1', ''): 'l_side',
 ('scars/head/heroscar15', '', ''): 'l_side',
 ('scars/head/heroscar16', 'v1', ''): 'l_side',
 ('scars/head/heroscar17', 'v1', ''): 'l_side'}
SCARCAMERASETINGS = {'l_eye': ('fj_eyeballLeft', (0.25,
            0,
            0,
            pi05 + 0.15,
            pi05 - 0.07), 'SoftCenterRimSides'),
 'r_eye': ('fj_eyeballRight', (0.25,
            0,
            0,
            pi05 + 0.15,
            pi05 - 0.07), 'SoftCenterRimSides'),
 'mouth': ('fj_lip_lower_center', (0.2,
            0,
            0,
            pi05 + 0.4,
            pi05 + 0.05), 'SoftCenterRimSides'),
 'l_cheek': ('Head', (0.6,
              0,
              0,
              pi05 - 0.6,
              pi05 + 0.3), 'softLeft'),
 'r_cheek': ('Head', (0.6,
              0,
              0,
              pi05 + 0.5,
              pi05 + 0.3), 'softRight'),
 'l_side': ('Head', (0.65,
             0.025,
             -0.05,
             pi05 - 0.9,
             pi05 + 0.3), 'softLeft'),
 'r_side': ('Head', (0.65,
             0.025,
             0.05,
             pi05 + 1.0,
             pi05 + 0.3), 'softRight'),
 'nose': ('fj_nose_left', (0.25,
           0.015,
           -0.01,
           pi05 - 0.2,
           pi05 + 0.3), 'SoftCenterRimSides'),
 'chin': ('fj_lip_lower_center', (0.25,
           0,
           0,
           pi05 + 0.4,
           pi05 + 0.05), 'SoftCenterRimSides'),
 'forhead': ('fj_foreheadLower_centerLeft', (0.35,
              0,
              -0.018,
              pi05 - 0.05,
              pi05), 'SoftCenterRimSides')}
MALE_MANNEQUIN = 'res:/Graphics/Character/DNAFiles/Mannequin/MaleMannequin.prs'
FEMALE_MANNEQUIN = 'res:/Graphics/Character/DNAFiles/Mannequin/FemaleMannequin.prs'
LIGHTLOCATION = 'res:/Graphics/Character/Global/PaperdollSettings/LightSettings/assetRenderer/'
NORMAL_LIGHT_SETTINGS = 'res:/Graphics/Character/Global/PaperdollSettings/LightSettings/assetRenderer/Normal.red'
NORMAL_LIGHT_COLOR = 'res:/Graphics/Character/Global/PaperdollSettings/LightSettings/Normal.red'
PIERCINGCATEGORIES = (ccConst.p_lips,
 ccConst.p_brow,
 ccConst.p_nostril,
 ccConst.p_nose,
 ccConst.p_earshigh,
 ccConst.p_earslow,
 ccConst.p_chin)
PIERCINGRIGHTGROUPS = {ccConst.p_earslow: ('fj_ear_wiggle', (0.3,
                      -0.01,
                      0,
                      pi + 0.1,
                      pi05), 'softRight'),
 ccConst.p_earshigh: ('fj_ear_wiggle', (0.27,
                       0,
                       0,
                       pi + 0.2,
                       pi05), 'softRight'),
 ccConst.p_nose: ('fj_nose_left', (0.25,
                   0.02,
                   -0.01,
                   pi05 - 0.2,
                   pi05 + 0.3), 'SoftCenterRimSides'),
 ccConst.p_nostril: ('fj_nose_left', (0.2,
                      -0.01,
                      -0.01,
                      pi05 + 0.35,
                      pi05 + 0.2), 'SoftCenterRimSides'),
 ccConst.p_brow: ('fj_eyeballRight', (0.18,
                   0.005,
                   -0.005,
                   pi05 + 0.15,
                   pi05 - 0.07), 'SoftCenterRimSides'),
 ccConst.p_lips: ('fj_lip_lower_center', (0.2,
                   0,
                   0,
                   pi05 + 0.4,
                   pi05 + 0.05), 'SoftCenterRimSides'),
 ccConst.p_chin: ('fj_lip_lower_center', (0.2,
                   0,
                   0,
                   pi05 + 0.4,
                   pi05 + 0.05), 'SoftCenterRimSides')}
PIERCINGLEFTGROUPS = {ccConst.p_earslow: ('fj_ear_wiggle', (0.3,
                      -0.01,
                      0,
                      -0.06,
                      pi05), 'softLeft'),
 ccConst.p_earshigh: ('fj_ear_wiggle', (0.27,
                       0,
                       0,
                       -0.08,
                       pi05), 'softLeft'),
 ccConst.p_nose: ('fj_nose_left', (0.25,
                   0.02,
                   -0.01,
                   pi05 - 0.2,
                   pi05 + 0.3), 'SoftCenterRimSides'),
 ccConst.p_nostril: ('fj_nose_left', (0.2,
                      -0.01,
                      -0.01,
                      pi05 + 0.35,
                      pi05 + 0.2), 'SoftCenterRimSides'),
 ccConst.p_brow: ('fj_eyeballLeft', (0.18,
                   0.005,
                   +0.005,
                   pi05 + 0.15,
                   pi05 - 0.07), 'SoftCenterRimSides'),
 ccConst.p_lips: ('fj_lip_lower_center', (0.2,
                   0,
                   0,
                   pi05 + 0.4,
                   pi05 + 0.05), 'SoftCenterRimSides'),
 ccConst.p_chin: ('fj_lip_lower_center', (0.2,
                   0,
                   0,
                   pi05 + 0.4,
                   pi05 + 0.05), 'SoftCenterRimSides')}
PIERCINGPAIRGROUPS = {ccConst.p_earslow: ('Head_End', (0.65,
                      -0.14,
                      0,
                      pi05 - 0.05,
                      pi05), 'SoftCenterRimSides'),
 ccConst.p_earshigh: ('Head_End', (0.65,
                       -0.14,
                       0,
                       pi05 - 0.05,
                       pi05), 'SoftCenterRimSides'),
 ccConst.p_nose: ('fj_nose_left', (0.25,
                   0.02,
                   -0.01,
                   pi05 - 0.2,
                   pi05 + 0.3), 'SoftCenterRimSides'),
 ccConst.p_nostril: ('fj_nose_left', (0.2,
                      -0.01,
                      -0.01,
                      pi05 + 0.35,
                      pi05 + 0.2), 'SoftCenterRimSides'),
 ccConst.p_brow: ('Head_End', (0.65,
                   -0.14,
                   0,
                   pi05 - 0.05,
                   pi05), 'SoftCenterRimSides'),
 ccConst.p_lips: ('fj_lip_lower_center', (0.2,
                   0,
                   0,
                   pi05 + 0.4,
                   pi05 + 0.05), 'SoftCenterRimSides'),
 ccConst.p_chin: ('fj_lip_lower_center', (0.2,
                   0,
                   0,
                   pi05 + 0.4,
                   pi05 + 0.05), 'SoftCenterRimSides')}
