#Embedded file name: eve/client/script/parklife\sceneManagerConsts.py
SCENE_TYPE_CHARACTER_CREATION = 0
SCENE_TYPE_INTERIOR = 1
SCENE_TYPE_SPACE = 2
exports = {'sceneManager.SCENE_TYPE_SPACE': SCENE_TYPE_SPACE,
 'sceneManager.SCENE_TYPE_CHARACTER_CREATION': SCENE_TYPE_CHARACTER_CREATION,
 'sceneManager.SCENE_TYPE_INTERIOR': SCENE_TYPE_INTERIOR}
