#Embedded file name: eve/client/script/environment/effects\effectConsts.py
FX_MERGE_GUID = 1
FX_MERGE_SHIP = 2
FX_MERGE_MODULE = 3
FX_MERGE_TARGET = 4
FX_TF_NONE = 0
FX_TF_POSITION_BALL = 1
FX_TF_POSITION_MODEL = 7
FX_TF_POSITION_TARGET = 2
FX_TF_ROTATION_BALL = 3
FX_TF_SCALE_SYMMETRIC = 4
FX_TF_SCALE_BOUNDING = 5
FX_TF_SCALE_RADIUS = 6
