#Embedded file name: spacecomponents/common\componentConst.py
"""
component names
"""
DEPLOY_CLASS = 'deploy'
ACTIVATE_CLASS = 'activate'
DOGMATIC_CLASS = 'dogmatic'
SCOOP_CLASS = 'scoop'
DECAY_CLASS = 'decay'
FITTING_CLASS = 'fitting'
CARGO_BAY = 'cargoBay'
CYNO_INHIBITOR_CLASS = 'cynoInhibitor'
REINFORCE_CLASS = 'reinforce'
AUTO_TRACTOR_BEAM_CLASS = 'autoTractorBeam'
AUTO_LOOTER_CLASS = 'autoLooter'
BOOKMARK_CLASS = 'bookmark'
SIPHON_CLASS = 'siphon'
BOUNTYESCROW_CLASS = 'bountyEscrow'
PHYSICS_CLASS = 'physics'
SCAN_BLOCKER_CLASS = 'scanBlocker'
MICRO_JUMP_DRIVER_CLASS = 'microJumpDriver'
WARP_DISRUPTION_CLASS = 'warpDisruption'
BEHAVIOR = 'behavior'
NPC_PILOT = 'npcpilot'
TURBO_SHIELD_CLASS = 'turboShield'
PROXIMITY_SENSOR_CLASS = 'proximitySensor'
ALL_COMPONENTS = (DEPLOY_CLASS,
 ACTIVATE_CLASS,
 DOGMATIC_CLASS,
 SCOOP_CLASS,
 DECAY_CLASS,
 FITTING_CLASS,
 CARGO_BAY,
 CYNO_INHIBITOR_CLASS,
 REINFORCE_CLASS,
 AUTO_TRACTOR_BEAM_CLASS,
 AUTO_LOOTER_CLASS,
 BOOKMARK_CLASS,
 SIPHON_CLASS,
 BOUNTYESCROW_CLASS,
 PHYSICS_CLASS,
 SCAN_BLOCKER_CLASS,
 MICRO_JUMP_DRIVER_CLASS,
 WARP_DISRUPTION_CLASS,
 BEHAVIOR,
 NPC_PILOT,
 TURBO_SHIELD_CLASS,
 PROXIMITY_SENSOR_CLASS)
MIN_DISTANCE_FROM_CONTROLTOWER_MAX_VALUE = 500000
