#Embedded file name: workers\const.py
"""
Teams constants.
"""
from carbon.common.lib.const import WEEK
from industry import MANUFACTURING, RESEARCH_MATERIAL, RESEARCH_TIME, COPYING, INVENTION
from workers.specialization import Specialization
ACT_MANUFACTURING = MANUFACTURING
ACT_MATERIALRESEARCH = RESEARCH_MATERIAL
ACT_TIMERESEARCH = RESEARCH_TIME
ACT_COPYING = COPYING
ACT_INVENTION = INVENTION
TEAM_EXPIRY_TIME = 35
RANGE_WORLD = 0
RANGE_SOLAR_SYSTEM = 1
RANGE_REGION = 2
RANGE_FACILITY_LOCATION = 3
RANGES = (RANGE_FACILITY_LOCATION,
 RANGE_SOLAR_SYSTEM,
 RANGE_REGION,
 RANGE_WORLD)
TYPE_STRUCTURE = 1
TYPE_COMPONENT = 2
TYPE_CONSUMABLE = 3
TYPE_SHIP = 4
TYPE_MOBILE = 5
TYPE_EQUIPMENT = 6
TEAM_TYPES = (TYPE_STRUCTURE,
 TYPE_COMPONENT,
 TYPE_CONSUMABLE,
 TYPE_SHIP,
 TYPE_MOBILE,
 TYPE_EQUIPMENT)
AUCTION_EXPIRY_TIME = WEEK
AUCTION_DISTANCE_COST = 10000
AUCTION_WORMHOLE_COST = 50 * AUCTION_DISTANCE_COST
TEAM_SPAWN_DELAY = 10
SPE_STARBASE = 7
SPE_DEPLOYABLES = 8
SPE_SOVEREIGNTY = 9
SPE_CONTAINERS = 10
SPE_SUBSYSTEM = 11
SPE_CAPITAL_CONSTRUCTION = 12
SPE_OUTPOST_COMPONENTS = 13
SPE_TOOLS = 14
SPE_HYBRID = 15
SPE_DATA_INTERFACES = 16
SPE_CONSTRUCTION_COMPONENTS = 141
SPE_AMMO = 17
SPE_CAPACITOR_BOOSTERS = 18
SPE_FUEL_BLOCK = 19
SPE_NANITE_PASTE = 20
SPE_NEURAL_BOOSTERS = 21
SPE_INTERDICTION_PROBE = 63
SPE_SMALL_CLASS = 22
SPE_MEDIUM_CLASS = 23
SPE_LARGE_CLASS = 24
SPE_CAPITAL_CLASS = 25
SPE_DISRUPTION_DRONES = 26
SPE_WARFARE_DRONES = 27
SPE_FIGHTERS = 28
SPE_UTILITY_DRONES = 29
SPE_SCANNER_PROBE = 30
SPE_SURVEY_PROBE = 31
SPE_ARMOR = 32
SPE_SHIELDS = 33
SPE_ELECTRONIC_WARFARE = 34
SPE_TURRETS_MISSILE_DAMAGE = 35
SPE_ENGINEERING = 36
SPE_NAVIGATION = 37
SPE_SENSOR_TARGETING = 38
SPE_DRONE_MODULES = 39
SPE_SCANNERS_HARVESTING = 40
SPE_RIGS = 41
SPE_IMPLANTS = 42
SPE_SCRIPTS = 43
SPE_STARBASE_CORE = 44
SPE_STARBASE_WEAPONS = 49
SPE_STARBASE_DEFENSE = 45
SPE_STARBASE_PROCESSING = 46
SPE_STARBASE_PRODUCTION = 47
SPE_STARBASE_STORAGE = 48
SPE_MOBILE_STRUCTURES = 50
SPE_MOBILE_DISRUPTION = 51
SPE_I_HUBS = 52
SPE_SBUS = 53
SPE_TCUS = 54
SPE_DEFENSE_SYSTEMS = 55
SPE_ELECTRONIC_SYSTEMS = 56
SPE_ENGINEERING_SYSTEMS = 57
SPE_OFFENSIVE_SYSTEMS = 58
SPE_PROPULSION_SYSTEMS = 59
SPE_BOMBS = 60
SPE_FREQ_MINING_CRYSTAL_ADV = 61
SPE_HYBRID_AMMO_ADV = 62
SPE_MISSILES_TORP_ROCKET = 64
SPE_PROJECTILE_AMMO = 65
SPE_ASSAULT_FRIGATE = 66
SPE_COVERT_OPS = 67
SPE_DESTROYER = 68
SPE_ELECTRONIC_ATTACK_SHIP = 69
SPE_FRIGATE = 70
SPE_INTERCEPTOR = 71
SPE_INTERDICTOR = 72
SPE_SHUTTLE = 73
SPE_BATTLECRUISER = 74
SPE_COMMAND_SHIP = 75
SPE_CRUISER = 76
SPE_INDUSTRIAL_SHIPS = 77
SPE_HEAVY_ASSAULT_CRUISERS = 78
SPE_HEAVY_INTERDICTION_CRUISERS = 79
SPE_LOGISTICS = 80
SPE_MINING_BARGE = 81
SPE_RECON_SHIPS = 82
SPE_STRATEGIC_CRUISER = 83
SPE_BATTLESHIP = 84
SPE_BLACK_OPS = 85
SPE_MARAUDER = 86
SPE_CAPITAL_INDUSTRIAL_SHIP = 87
SPE_CARRIER = 88
SPE_DREADNOUGHT = 89
SPE_FREIGHTERS = 90
SPE_SUPERCARRIER = 91
SPE_TITAN = 92
SPE_INDUSTRIAL_COMMAND_SHIPS = 139
SPE_CAP_DRAIN_DRONE = 93
SPE_EW_DRONE = 94
SPE_STASIS_WEBIFYING_DRONE = 95
SPE_COMBAT_DRONE = 96
SPE_FIGHTER_BOMBER = 97
SPE_FIGHTER_DRONE = 98
SPE_LOGISTICS_DRONE = 99
SPE_MINING_DRONE = 100
SPE_SALVAGE_DRONE = 101
SPE_ARMOR_ACTIVE_MODULES = 102
SPE_ARMOR_PASSIVE_EXPANDERS = 103
SPE_ARMOR_PASSIVE_RESISTANCE = 104
SPE_SHIELD_ACTIVE_MODULES = 107
SPE_SHIELD_PASSIVE_RECHARGE = 140
SPE_SHIELD_PASSIVE_EXTENDERS = 105
SPE_SHIELD_PASSIVE_RESISTANCE = 106
SPE_ECM_ECCM = 108
SPE_ENERGY_DRAIN_MODULES = 109
SPE_TRACKING_DISRUPTOR = 110
SPE_WARP_SCRAMBLING_MODULES = 111
SPE_DAMAGE_AMPLIFIERS = 112
SPE_ENERGY_WEAPON = 113
SPE_HYBRID_WEAPON = 114
SPE_MISSILE_LAUNCHERS = 115
SPE_PROJECTILE_WEAPON = 116
SPE_SMART_BOMB = 117
SPE_CAPACITOR_ACTIVE = 118
SPE_CAPACITOR_PASSIVE = 119
SPE_CAPITAL_MODULES = 120
SPE_DAMAGE_CONTROL = 121
SPE_FITTING_MODULES = 122
SPE_HULL_MODULES = 123
SPE_CLOAKING_DEVICE = 124
SPE_JUMP_MODULES = 125
SPE_PROPULSION_MODULES = 126
SPE_STASIS_WEB = 127
SPE_STABILIZER_MODULES = 128
SPE_FLEET_COORDINATOR = 129
SPE_REMOTE_MODULES = 130
SPE_TARGETING_MODULES = 131
SPE_TRACKING_MODULES = 132
SPE_TRACTOR_BEAM = 133
SPE_DRONE_OPERATION_MODULES = 134
SPE_DRONE_EFFECTIVENESS_MODULES = 135
SPE_HARVESTING_MODULES = 136
SPE_SCANNING_MODULES = 137
SPE_SURVEYING_MODULES = 138

class Node:

    def __init__(self, nodeID, tier, childrenIDs):
        self.nodeID = nodeID
        self.tier = tier
        self.childrenIDs = childrenIDs


SPECIALIZATION_TREE = {}
SPECIALIZATION_TREE[0] = Node(0, 0, [TYPE_STRUCTURE,
 TYPE_COMPONENT,
 TYPE_CONSUMABLE,
 TYPE_SHIP,
 TYPE_MOBILE,
 TYPE_EQUIPMENT])
SPECIALIZATION_TREE[TYPE_STRUCTURE] = Node(TYPE_STRUCTURE, 1, [SPE_STARBASE,
 SPE_DEPLOYABLES,
 SPE_SOVEREIGNTY,
 SPE_CONTAINERS])
SPECIALIZATION_TREE[TYPE_COMPONENT] = Node(TYPE_COMPONENT, 1, [SPE_SUBSYSTEM,
 SPE_CAPITAL_CONSTRUCTION,
 SPE_OUTPOST_COMPONENTS,
 SPE_TOOLS,
 SPE_HYBRID,
 SPE_DATA_INTERFACES,
 SPE_CONSTRUCTION_COMPONENTS])
SPECIALIZATION_TREE[TYPE_CONSUMABLE] = Node(TYPE_CONSUMABLE, 1, [SPE_AMMO,
 SPE_CAPACITOR_BOOSTERS,
 SPE_FUEL_BLOCK,
 SPE_NANITE_PASTE,
 SPE_NEURAL_BOOSTERS,
 SPE_INTERDICTION_PROBE])
SPECIALIZATION_TREE[TYPE_SHIP] = Node(TYPE_SHIP, 1, [SPE_SMALL_CLASS,
 SPE_MEDIUM_CLASS,
 SPE_LARGE_CLASS,
 SPE_CAPITAL_CLASS])
SPECIALIZATION_TREE[TYPE_MOBILE] = Node(TYPE_MOBILE, 1, [SPE_DISRUPTION_DRONES,
 SPE_WARFARE_DRONES,
 SPE_FIGHTERS,
 SPE_UTILITY_DRONES,
 SPE_SCANNER_PROBE,
 SPE_SURVEY_PROBE])
SPECIALIZATION_TREE[TYPE_EQUIPMENT] = Node(TYPE_EQUIPMENT, 1, [SPE_ARMOR,
 SPE_SHIELDS,
 SPE_ELECTRONIC_WARFARE,
 SPE_TURRETS_MISSILE_DAMAGE,
 SPE_ENGINEERING,
 SPE_NAVIGATION,
 SPE_SENSOR_TARGETING,
 SPE_DRONE_MODULES,
 SPE_SCANNERS_HARVESTING,
 SPE_RIGS,
 SPE_IMPLANTS,
 SPE_SCRIPTS])
SPECIALIZATION_TREE[SPE_STARBASE] = Node(SPE_STARBASE, 2, [SPE_STARBASE_CORE,
 SPE_STARBASE_DEFENSE,
 SPE_STARBASE_PROCESSING,
 SPE_STARBASE_PRODUCTION,
 SPE_STARBASE_WEAPONS])
SPECIALIZATION_TREE[SPE_DEPLOYABLES] = Node(SPE_DEPLOYABLES, 2, [SPE_MOBILE_STRUCTURES, SPE_MOBILE_DISRUPTION])
SPECIALIZATION_TREE[SPE_SOVEREIGNTY] = Node(SPE_SOVEREIGNTY, 2, [SPE_I_HUBS, SPE_SBUS, SPE_TCUS])
SPECIALIZATION_TREE[SPE_CONTAINERS] = Node(SPE_CONTAINERS, 2, [])
SPECIALIZATION_TREE[SPE_SUBSYSTEM] = Node(SPE_SUBSYSTEM, 2, [SPE_DEFENSE_SYSTEMS,
 SPE_ELECTRONIC_SYSTEMS,
 SPE_ENGINEERING_SYSTEMS,
 SPE_OFFENSIVE_SYSTEMS,
 SPE_PROPULSION_SYSTEMS])
SPECIALIZATION_TREE[SPE_CAPITAL_CONSTRUCTION] = Node(SPE_CAPITAL_CONSTRUCTION, 2, [])
SPECIALIZATION_TREE[SPE_OUTPOST_COMPONENTS] = Node(SPE_OUTPOST_COMPONENTS, 2, [])
SPECIALIZATION_TREE[SPE_TOOLS] = Node(SPE_TOOLS, 2, [])
SPECIALIZATION_TREE[SPE_HYBRID] = Node(SPE_HYBRID, 2, [])
SPECIALIZATION_TREE[SPE_DATA_INTERFACES] = Node(SPE_DATA_INTERFACES, 2, [])
SPECIALIZATION_TREE[SPE_CONSTRUCTION_COMPONENTS] = Node(SPE_CONSTRUCTION_COMPONENTS, 2, [])
SPECIALIZATION_TREE[SPE_AMMO] = Node(SPE_AMMO, 2, [SPE_BOMBS,
 SPE_FREQ_MINING_CRYSTAL_ADV,
 SPE_HYBRID_AMMO_ADV,
 SPE_INTERDICTION_PROBE,
 SPE_MISSILES_TORP_ROCKET,
 SPE_PROJECTILE_AMMO])
SPECIALIZATION_TREE[SPE_CAPACITOR_BOOSTERS] = Node(SPE_CAPACITOR_BOOSTERS, 2, [])
SPECIALIZATION_TREE[SPE_FUEL_BLOCK] = Node(SPE_FUEL_BLOCK, 2, [])
SPECIALIZATION_TREE[SPE_NANITE_PASTE] = Node(SPE_NANITE_PASTE, 2, [])
SPECIALIZATION_TREE[SPE_NEURAL_BOOSTERS] = Node(SPE_NEURAL_BOOSTERS, 2, [])
SPECIALIZATION_TREE[SPE_SMALL_CLASS] = Node(SPE_SMALL_CLASS, 2, [SPE_ASSAULT_FRIGATE,
 SPE_COVERT_OPS,
 SPE_DESTROYER,
 SPE_ELECTRONIC_ATTACK_SHIP,
 SPE_FRIGATE,
 SPE_INTERCEPTOR,
 SPE_INTERDICTOR,
 SPE_SHUTTLE])
SPECIALIZATION_TREE[SPE_MEDIUM_CLASS] = Node(SPE_MEDIUM_CLASS, 2, [SPE_BATTLECRUISER,
 SPE_COMMAND_SHIP,
 SPE_CRUISER,
 SPE_INDUSTRIAL_SHIPS,
 SPE_HEAVY_ASSAULT_CRUISERS,
 SPE_HEAVY_INTERDICTION_CRUISERS,
 SPE_LOGISTICS,
 SPE_MINING_BARGE,
 SPE_RECON_SHIPS,
 SPE_STRATEGIC_CRUISER])
SPECIALIZATION_TREE[SPE_LARGE_CLASS] = Node(SPE_LARGE_CLASS, 2, [SPE_BATTLESHIP,
 SPE_BLACK_OPS,
 SPE_MARAUDER,
 SPE_INDUSTRIAL_COMMAND_SHIPS])
SPECIALIZATION_TREE[SPE_CAPITAL_CLASS] = Node(SPE_CAPITAL_CLASS, 2, [SPE_CARRIER,
 SPE_DREADNOUGHT,
 SPE_FREIGHTERS,
 SPE_SUPERCARRIER,
 SPE_TITAN])
SPECIALIZATION_TREE[SPE_DISRUPTION_DRONES] = Node(SPE_DISRUPTION_DRONES, 2, [SPE_CAP_DRAIN_DRONE, SPE_EW_DRONE, SPE_STASIS_WEBIFYING_DRONE])
SPECIALIZATION_TREE[SPE_WARFARE_DRONES] = Node(SPE_WARFARE_DRONES, 2, [SPE_COMBAT_DRONE])
SPECIALIZATION_TREE[SPE_FIGHTERS] = Node(SPE_FIGHTERS, 2, [SPE_FIGHTER_BOMBER, SPE_FIGHTER_DRONE])
SPECIALIZATION_TREE[SPE_UTILITY_DRONES] = Node(SPE_UTILITY_DRONES, 2, [SPE_LOGISTICS_DRONE, SPE_MINING_DRONE, SPE_SALVAGE_DRONE])
SPECIALIZATION_TREE[SPE_SCANNER_PROBE] = Node(SPE_SCANNER_PROBE, 2, [])
SPECIALIZATION_TREE[SPE_SURVEY_PROBE] = Node(SPE_SURVEY_PROBE, 2, [])
SPECIALIZATION_TREE[SPE_ARMOR] = Node(SPE_ARMOR, 2, [SPE_ARMOR_ACTIVE_MODULES, SPE_ARMOR_PASSIVE_EXPANDERS, SPE_ARMOR_PASSIVE_RESISTANCE])
SPECIALIZATION_TREE[SPE_SHIELDS] = Node(SPE_SHIELDS, 2, [SPE_SHIELD_PASSIVE_EXTENDERS, SPE_SHIELD_PASSIVE_RESISTANCE, SPE_SHIELD_ACTIVE_MODULES])
SPECIALIZATION_TREE[SPE_ELECTRONIC_WARFARE] = Node(SPE_ELECTRONIC_WARFARE, 2, [SPE_ECM_ECCM,
 SPE_ENERGY_DRAIN_MODULES,
 SPE_TRACKING_DISRUPTOR,
 SPE_WARP_SCRAMBLING_MODULES])
SPECIALIZATION_TREE[SPE_TURRETS_MISSILE_DAMAGE] = Node(SPE_TURRETS_MISSILE_DAMAGE, 2, [SPE_DAMAGE_AMPLIFIERS,
 SPE_ENERGY_WEAPON,
 SPE_HYBRID_WEAPON,
 SPE_MISSILE_LAUNCHERS,
 SPE_PROJECTILE_WEAPON,
 SPE_SMART_BOMB])
SPECIALIZATION_TREE[SPE_ENGINEERING] = Node(SPE_ENGINEERING, 2, [SPE_CAPACITOR_ACTIVE,
 SPE_CAPACITOR_PASSIVE,
 SPE_CAPITAL_MODULES,
 SPE_DAMAGE_CONTROL,
 SPE_FITTING_MODULES,
 SPE_HULL_MODULES])
SPECIALIZATION_TREE[SPE_NAVIGATION] = Node(SPE_NAVIGATION, 2, [SPE_CLOAKING_DEVICE,
 SPE_JUMP_MODULES,
 SPE_PROPULSION_MODULES,
 SPE_STASIS_WEB,
 SPE_STABILIZER_MODULES])
SPECIALIZATION_TREE[SPE_SENSOR_TARGETING] = Node(SPE_SENSOR_TARGETING, 2, [SPE_FLEET_COORDINATOR,
 SPE_REMOTE_MODULES,
 SPE_TARGETING_MODULES,
 SPE_TRACKING_MODULES,
 SPE_TRACTOR_BEAM])
SPECIALIZATION_TREE[SPE_DRONE_MODULES] = Node(SPE_DRONE_MODULES, 2, [SPE_DRONE_OPERATION_MODULES, SPE_DRONE_EFFECTIVENESS_MODULES])
SPECIALIZATION_TREE[SPE_SCANNERS_HARVESTING] = Node(SPE_SCANNERS_HARVESTING, 2, [SPE_HARVESTING_MODULES, SPE_SCANNING_MODULES, SPE_SURVEYING_MODULES])
SPECIALIZATION_TREE[SPE_RIGS] = Node(SPE_RIGS, 2, [])
SPECIALIZATION_TREE[SPE_IMPLANTS] = Node(SPE_IMPLANTS, 2, [])
SPECIALIZATION_TREE[SPE_SCRIPTS] = Node(SPE_SCRIPTS, 2, [])
SPECIALIZATION_TREE[SPE_STARBASE_CORE] = Node(SPE_STARBASE_CORE, 3, [])
SPECIALIZATION_TREE[SPE_STARBASE_DEFENSE] = Node(SPE_STARBASE_DEFENSE, 3, [])
SPECIALIZATION_TREE[SPE_STARBASE_PROCESSING] = Node(SPE_STARBASE_PROCESSING, 3, [])
SPECIALIZATION_TREE[SPE_STARBASE_PRODUCTION] = Node(SPE_STARBASE_PRODUCTION, 3, [])
SPECIALIZATION_TREE[SPE_STARBASE_STORAGE] = Node(SPE_STARBASE_STORAGE, 3, [])
SPECIALIZATION_TREE[SPE_STARBASE_WEAPONS] = Node(SPE_STARBASE_WEAPONS, 3, [])
SPECIALIZATION_TREE[SPE_MOBILE_STRUCTURES] = Node(SPE_MOBILE_STRUCTURES, 3, [])
SPECIALIZATION_TREE[SPE_MOBILE_DISRUPTION] = Node(SPE_MOBILE_DISRUPTION, 3, [])
SPECIALIZATION_TREE[SPE_I_HUBS] = Node(SPE_I_HUBS, 3, [])
SPECIALIZATION_TREE[SPE_SBUS] = Node(SPE_SBUS, 3, [])
SPECIALIZATION_TREE[SPE_TCUS] = Node(SPE_TCUS, 3, [])
SPECIALIZATION_TREE[SPE_DEFENSE_SYSTEMS] = Node(SPE_DEFENSE_SYSTEMS, 3, [])
SPECIALIZATION_TREE[SPE_ELECTRONIC_SYSTEMS] = Node(SPE_ELECTRONIC_SYSTEMS, 3, [])
SPECIALIZATION_TREE[SPE_ENGINEERING_SYSTEMS] = Node(SPE_ENGINEERING_SYSTEMS, 3, [])
SPECIALIZATION_TREE[SPE_OFFENSIVE_SYSTEMS] = Node(SPE_OFFENSIVE_SYSTEMS, 3, [])
SPECIALIZATION_TREE[SPE_PROPULSION_SYSTEMS] = Node(SPE_PROPULSION_SYSTEMS, 3, [])
SPECIALIZATION_TREE[SPE_BOMBS] = Node(SPE_BOMBS, 3, [])
SPECIALIZATION_TREE[SPE_FREQ_MINING_CRYSTAL_ADV] = Node(SPE_FREQ_MINING_CRYSTAL_ADV, 3, [])
SPECIALIZATION_TREE[SPE_HYBRID_AMMO_ADV] = Node(SPE_HYBRID_AMMO_ADV, 3, [])
SPECIALIZATION_TREE[SPE_INTERDICTION_PROBE] = Node(SPE_INTERDICTION_PROBE, 3, [])
SPECIALIZATION_TREE[SPE_MISSILES_TORP_ROCKET] = Node(SPE_MISSILES_TORP_ROCKET, 3, [])
SPECIALIZATION_TREE[SPE_PROJECTILE_AMMO] = Node(SPE_PROJECTILE_AMMO, 3, [])
SPECIALIZATION_TREE[SPE_ASSAULT_FRIGATE] = Node(SPE_ASSAULT_FRIGATE, 3, [])
SPECIALIZATION_TREE[SPE_COVERT_OPS] = Node(SPE_COVERT_OPS, 3, [])
SPECIALIZATION_TREE[SPE_DESTROYER] = Node(SPE_DESTROYER, 3, [])
SPECIALIZATION_TREE[SPE_ELECTRONIC_ATTACK_SHIP] = Node(SPE_ELECTRONIC_ATTACK_SHIP, 3, [])
SPECIALIZATION_TREE[SPE_FRIGATE] = Node(SPE_FRIGATE, 3, [])
SPECIALIZATION_TREE[SPE_INTERCEPTOR] = Node(SPE_INTERCEPTOR, 3, [])
SPECIALIZATION_TREE[SPE_INTERDICTOR] = Node(SPE_INTERDICTOR, 3, [])
SPECIALIZATION_TREE[SPE_SHUTTLE] = Node(SPE_SHUTTLE, 3, [])
SPECIALIZATION_TREE[SPE_BATTLECRUISER] = Node(SPE_BATTLECRUISER, 3, [])
SPECIALIZATION_TREE[SPE_COMMAND_SHIP] = Node(SPE_COMMAND_SHIP, 3, [])
SPECIALIZATION_TREE[SPE_CRUISER] = Node(SPE_CRUISER, 3, [])
SPECIALIZATION_TREE[SPE_INDUSTRIAL_SHIPS] = Node(SPE_INDUSTRIAL_SHIPS, 3, [])
SPECIALIZATION_TREE[SPE_INDUSTRIAL_COMMAND_SHIPS] = Node(SPE_INDUSTRIAL_COMMAND_SHIPS, 3, [])
SPECIALIZATION_TREE[SPE_HEAVY_ASSAULT_CRUISERS] = Node(SPE_HEAVY_ASSAULT_CRUISERS, 3, [])
SPECIALIZATION_TREE[SPE_HEAVY_INTERDICTION_CRUISERS] = Node(SPE_HEAVY_INTERDICTION_CRUISERS, 3, [])
SPECIALIZATION_TREE[SPE_LOGISTICS] = Node(SPE_LOGISTICS, 3, [])
SPECIALIZATION_TREE[SPE_MINING_BARGE] = Node(SPE_MINING_BARGE, 3, [])
SPECIALIZATION_TREE[SPE_RECON_SHIPS] = Node(SPE_RECON_SHIPS, 3, [])
SPECIALIZATION_TREE[SPE_STRATEGIC_CRUISER] = Node(SPE_STRATEGIC_CRUISER, 3, [])
SPECIALIZATION_TREE[SPE_BATTLESHIP] = Node(SPE_BATTLESHIP, 3, [])
SPECIALIZATION_TREE[SPE_BLACK_OPS] = Node(SPE_BLACK_OPS, 3, [])
SPECIALIZATION_TREE[SPE_MARAUDER] = Node(SPE_MARAUDER, 3, [])
SPECIALIZATION_TREE[SPE_CAPITAL_INDUSTRIAL_SHIP] = Node(SPE_CAPITAL_INDUSTRIAL_SHIP, 3, [])
SPECIALIZATION_TREE[SPE_CARRIER] = Node(SPE_CARRIER, 3, [])
SPECIALIZATION_TREE[SPE_DREADNOUGHT] = Node(SPE_DREADNOUGHT, 3, [])
SPECIALIZATION_TREE[SPE_FREIGHTERS] = Node(SPE_FREIGHTERS, 3, [])
SPECIALIZATION_TREE[SPE_SUPERCARRIER] = Node(SPE_SUPERCARRIER, 3, [])
SPECIALIZATION_TREE[SPE_TITAN] = Node(SPE_TITAN, 3, [])
SPECIALIZATION_TREE[SPE_CAP_DRAIN_DRONE] = Node(SPE_CAP_DRAIN_DRONE, 3, [])
SPECIALIZATION_TREE[SPE_EW_DRONE] = Node(SPE_EW_DRONE, 3, [])
SPECIALIZATION_TREE[SPE_STASIS_WEBIFYING_DRONE] = Node(SPE_STASIS_WEBIFYING_DRONE, 3, [])
SPECIALIZATION_TREE[SPE_COMBAT_DRONE] = Node(SPE_COMBAT_DRONE, 3, [])
SPECIALIZATION_TREE[SPE_FIGHTER_BOMBER] = Node(SPE_FIGHTER_BOMBER, 3, [])
SPECIALIZATION_TREE[SPE_FIGHTER_DRONE] = Node(SPE_FIGHTER_DRONE, 3, [])
SPECIALIZATION_TREE[SPE_LOGISTICS_DRONE] = Node(SPE_LOGISTICS_DRONE, 3, [])
SPECIALIZATION_TREE[SPE_MINING_DRONE] = Node(SPE_MINING_DRONE, 3, [])
SPECIALIZATION_TREE[SPE_SALVAGE_DRONE] = Node(SPE_SALVAGE_DRONE, 3, [])
SPECIALIZATION_TREE[SPE_ARMOR_ACTIVE_MODULES] = Node(SPE_ARMOR_ACTIVE_MODULES, 3, [])
SPECIALIZATION_TREE[SPE_ARMOR_PASSIVE_EXPANDERS] = Node(SPE_ARMOR_PASSIVE_EXPANDERS, 3, [])
SPECIALIZATION_TREE[SPE_ARMOR_PASSIVE_RESISTANCE] = Node(SPE_ARMOR_PASSIVE_RESISTANCE, 3, [])
SPECIALIZATION_TREE[SPE_SHIELD_PASSIVE_EXTENDERS] = Node(SPE_SHIELD_PASSIVE_EXTENDERS, 3, [])
SPECIALIZATION_TREE[SPE_SHIELD_PASSIVE_RESISTANCE] = Node(SPE_SHIELD_PASSIVE_RESISTANCE, 3, [])
SPECIALIZATION_TREE[SPE_SHIELD_ACTIVE_MODULES] = Node(SPE_SHIELD_ACTIVE_MODULES, 3, [])
SPECIALIZATION_TREE[SPE_ECM_ECCM] = Node(SPE_ECM_ECCM, 3, [])
SPECIALIZATION_TREE[SPE_ENERGY_DRAIN_MODULES] = Node(SPE_ENERGY_DRAIN_MODULES, 3, [])
SPECIALIZATION_TREE[SPE_TRACKING_DISRUPTOR] = Node(SPE_TRACKING_DISRUPTOR, 3, [])
SPECIALIZATION_TREE[SPE_WARP_SCRAMBLING_MODULES] = Node(SPE_WARP_SCRAMBLING_MODULES, 3, [])
SPECIALIZATION_TREE[SPE_DAMAGE_AMPLIFIERS] = Node(SPE_DAMAGE_AMPLIFIERS, 3, [])
SPECIALIZATION_TREE[SPE_ENERGY_WEAPON] = Node(SPE_ENERGY_WEAPON, 3, [])
SPECIALIZATION_TREE[SPE_HYBRID_WEAPON] = Node(SPE_HYBRID_WEAPON, 3, [])
SPECIALIZATION_TREE[SPE_MISSILE_LAUNCHERS] = Node(SPE_MISSILE_LAUNCHERS, 3, [])
SPECIALIZATION_TREE[SPE_PROJECTILE_WEAPON] = Node(SPE_PROJECTILE_WEAPON, 3, [])
SPECIALIZATION_TREE[SPE_SMART_BOMB] = Node(SPE_SMART_BOMB, 3, [])
SPECIALIZATION_TREE[SPE_CAPACITOR_ACTIVE] = Node(SPE_CAPACITOR_ACTIVE, 3, [])
SPECIALIZATION_TREE[SPE_CAPACITOR_PASSIVE] = Node(SPE_CAPACITOR_PASSIVE, 3, [])
SPECIALIZATION_TREE[SPE_CAPITAL_MODULES] = Node(SPE_CAPITAL_MODULES, 3, [])
SPECIALIZATION_TREE[SPE_DAMAGE_CONTROL] = Node(SPE_DAMAGE_CONTROL, 3, [])
SPECIALIZATION_TREE[SPE_FITTING_MODULES] = Node(SPE_FITTING_MODULES, 3, [])
SPECIALIZATION_TREE[SPE_HULL_MODULES] = Node(SPE_HULL_MODULES, 3, [])
SPECIALIZATION_TREE[SPE_CLOAKING_DEVICE] = Node(SPE_CLOAKING_DEVICE, 3, [])
SPECIALIZATION_TREE[SPE_JUMP_MODULES] = Node(SPE_JUMP_MODULES, 3, [])
SPECIALIZATION_TREE[SPE_PROPULSION_MODULES] = Node(SPE_PROPULSION_MODULES, 3, [])
SPECIALIZATION_TREE[SPE_STASIS_WEB] = Node(SPE_STASIS_WEB, 3, [])
SPECIALIZATION_TREE[SPE_STABILIZER_MODULES] = Node(SPE_STABILIZER_MODULES, 3, [])
SPECIALIZATION_TREE[SPE_FLEET_COORDINATOR] = Node(SPE_FLEET_COORDINATOR, 3, [])
SPECIALIZATION_TREE[SPE_REMOTE_MODULES] = Node(SPE_REMOTE_MODULES, 3, [])
SPECIALIZATION_TREE[SPE_TARGETING_MODULES] = Node(SPE_TARGETING_MODULES, 3, [])
SPECIALIZATION_TREE[SPE_TRACKING_MODULES] = Node(SPE_TRACKING_MODULES, 3, [])
SPECIALIZATION_TREE[SPE_TRACTOR_BEAM] = Node(SPE_TRACTOR_BEAM, 3, [])
SPECIALIZATION_TREE[SPE_DRONE_OPERATION_MODULES] = Node(SPE_DRONE_OPERATION_MODULES, 3, [])
SPECIALIZATION_TREE[SPE_DRONE_EFFECTIVENESS_MODULES] = Node(SPE_DRONE_EFFECTIVENESS_MODULES, 3, [])
SPECIALIZATION_TREE[SPE_HARVESTING_MODULES] = Node(SPE_HARVESTING_MODULES, 3, [])
SPECIALIZATION_TREE[SPE_SCANNING_MODULES] = Node(SPE_SCANNING_MODULES, 3, [])
SPECIALIZATION_TREE[SPE_SURVEYING_MODULES] = Node(SPE_SURVEYING_MODULES, 3, [])
SPE_LABELS = {}
SPE_LABELS[0] = 'UI/Industry/Specialities/Specializations'
SPE_LABELS[TYPE_COMPONENT] = 'UI/Industry/Specialities/Component'
SPE_LABELS[TYPE_EQUIPMENT] = 'UI/Industry/Specialities/Equipment'
SPE_LABELS[TYPE_SHIP] = 'UI/Industry/Specialities/Ship'
SPE_LABELS[TYPE_MOBILE] = 'UI/Industry/Specialities/Mobile'
SPE_LABELS[TYPE_CONSUMABLE] = 'UI/Industry/Specialities/Consumable'
SPE_LABELS[TYPE_STRUCTURE] = 'UI/Industry/Specialities/Structure'
SPE_LABELS[SPE_STARBASE] = 'UI/Industry/Specialities/Starbase'
SPE_LABELS[SPE_DEPLOYABLES] = 'UI/Industry/Specialities/Deployables'
SPE_LABELS[SPE_SOVEREIGNTY] = 'UI/Industry/Specialities/Sovereignty'
SPE_LABELS[SPE_CONTAINERS] = 'UI/Industry/Specialities/Containers'
SPE_LABELS[SPE_SUBSYSTEM] = 'UI/Industry/Specialities/Subsystem'
SPE_LABELS[SPE_CAPITAL_CONSTRUCTION] = 'UI/Industry/Specialities/CapitalConstruction'
SPE_LABELS[SPE_OUTPOST_COMPONENTS] = 'UI/Industry/Specialities/OutpostComponents'
SPE_LABELS[SPE_TOOLS] = 'UI/Industry/Specialities/Tools'
SPE_LABELS[SPE_HYBRID] = 'UI/Industry/Specialities/Hybrid'
SPE_LABELS[SPE_DATA_INTERFACES] = 'UI/Industry/Specialities/DataInterfaces'
SPE_LABELS[SPE_CONSTRUCTION_COMPONENTS] = 'UI/Industry/Specialities/ConstructionComponents'
SPE_LABELS[SPE_AMMO] = 'UI/Industry/Specialities/Ammo'
SPE_LABELS[SPE_CAPACITOR_BOOSTERS] = 'UI/Industry/Specialities/CapacitorBoosters'
SPE_LABELS[SPE_FUEL_BLOCK] = 'UI/Industry/Specialities/FuelBlocks'
SPE_LABELS[SPE_NANITE_PASTE] = 'UI/Industry/Specialities/NaniteRepairPaste'
SPE_LABELS[SPE_NEURAL_BOOSTERS] = 'UI/Industry/Specialities/NeuralBoosters'
SPE_LABELS[SPE_SMALL_CLASS] = 'UI/Industry/Specialities/Smallclass'
SPE_LABELS[SPE_MEDIUM_CLASS] = 'UI/Industry/Specialities/Mediumclass'
SPE_LABELS[SPE_LARGE_CLASS] = 'UI/Industry/Specialities/Largeclass'
SPE_LABELS[SPE_CAPITAL_CLASS] = 'UI/Industry/Specialities/Capitalclass'
SPE_LABELS[SPE_DISRUPTION_DRONES] = 'UI/Industry/Specialities/DisruptionDrones'
SPE_LABELS[SPE_WARFARE_DRONES] = 'UI/Industry/Specialities/WarfareDrones'
SPE_LABELS[SPE_FIGHTERS] = 'UI/Industry/Specialities/Fighters'
SPE_LABELS[SPE_UTILITY_DRONES] = 'UI/Industry/Specialities/UtilityDrones'
SPE_LABELS[SPE_SCANNER_PROBE] = 'UI/Industry/Specialities/ScannerProbe'
SPE_LABELS[SPE_SURVEY_PROBE] = 'UI/Industry/Specialities/SurveyProbe'
SPE_LABELS[SPE_ARMOR] = 'UI/Industry/Specialities/Armor'
SPE_LABELS[SPE_SHIELDS] = 'UI/Industry/Specialities/Shields'
SPE_LABELS[SPE_ELECTRONIC_WARFARE] = 'UI/Industry/Specialities/ElectronicWarfare'
SPE_LABELS[SPE_TURRETS_MISSILE_DAMAGE] = 'UI/Industry/Specialities/Damage'
SPE_LABELS[SPE_ENGINEERING] = 'UI/Industry/Specialities/Engineering'
SPE_LABELS[SPE_NAVIGATION] = 'UI/Industry/Specialities/Navigation'
SPE_LABELS[SPE_SENSOR_TARGETING] = 'UI/Industry/Specialities/SensorsTargeting'
SPE_LABELS[SPE_DRONE_MODULES] = 'UI/Industry/Specialities/DroneModules'
SPE_LABELS[SPE_SCANNERS_HARVESTING] = 'UI/Industry/Specialities/ScannersAndHarvesting'
SPE_LABELS[SPE_RIGS] = 'UI/Industry/Specialities/Rigs'
SPE_LABELS[SPE_IMPLANTS] = 'UI/Industry/Specialities/Implants'
SPE_LABELS[SPE_SCRIPTS] = 'UI/Industry/Specialities/Scripts'
SPE_LABELS[SPE_STARBASE_CORE] = 'UI/Industry/Specialities/StarbaseCore'
SPE_LABELS[SPE_STARBASE_WEAPONS] = 'UI/Industry/Specialities/StarbaseWeapons'
SPE_LABELS[SPE_STARBASE_DEFENSE] = 'UI/Industry/Specialities/StarbaseDefense'
SPE_LABELS[SPE_STARBASE_PROCESSING] = 'UI/Industry/Specialities/StarbaseProcessing'
SPE_LABELS[SPE_STARBASE_PRODUCTION] = 'UI/Industry/Specialities/StarbaseProduction'
SPE_LABELS[SPE_STARBASE_STORAGE] = 'UI/Industry/Specialities/StarbaseStorage'
SPE_LABELS[SPE_MOBILE_STRUCTURES] = 'UI/Industry/Specialities/MobileStructures'
SPE_LABELS[SPE_MOBILE_DISRUPTION] = 'UI/Industry/Specialities/MobileDisruption'
SPE_LABELS[SPE_I_HUBS] = 'UI/Industry/Specialities/IHubs'
SPE_LABELS[SPE_SBUS] = 'UI/Industry/Specialities/SBUs'
SPE_LABELS[SPE_TCUS] = 'UI/Industry/Specialities/TCUs'
SPE_LABELS[SPE_DEFENSE_SYSTEMS] = 'UI/Industry/Specialities/DefensiveSystems'
SPE_LABELS[SPE_ELECTRONIC_SYSTEMS] = 'UI/Industry/Specialities/ElectronicsSystems'
SPE_LABELS[SPE_ENGINEERING_SYSTEMS] = 'UI/Industry/Specialities/EngineeringSystems'
SPE_LABELS[SPE_OFFENSIVE_SYSTEMS] = 'UI/Industry/Specialities/OffensiveSystems'
SPE_LABELS[SPE_PROPULSION_SYSTEMS] = 'UI/Industry/Specialities/PropulsionSystems'
SPE_LABELS[SPE_BOMBS] = 'UI/Industry/Specialities/Bombs'
SPE_LABELS[SPE_FREQ_MINING_CRYSTAL_ADV] = 'UI/Industry/Specialities/Crystals'
SPE_LABELS[SPE_HYBRID_AMMO_ADV] = 'UI/Industry/Specialities/HybridAmmo'
SPE_LABELS[SPE_INTERDICTION_PROBE] = 'UI/Industry/Specialities/InterdictionProbe'
SPE_LABELS[SPE_MISSILES_TORP_ROCKET] = 'UI/Industry/Specialities/MissilesRockets'
SPE_LABELS[SPE_PROJECTILE_AMMO] = 'UI/Industry/Specialities/ProjectileAmmo'
SPE_LABELS[SPE_ASSAULT_FRIGATE] = 'UI/Industry/Specialities/AssaultFrigate'
SPE_LABELS[SPE_COVERT_OPS] = 'UI/Industry/Specialities/CovertOps'
SPE_LABELS[SPE_DESTROYER] = 'UI/Industry/Specialities/Destroyer'
SPE_LABELS[SPE_ELECTRONIC_ATTACK_SHIP] = 'UI/Industry/Specialities/ElectronicAttackShip'
SPE_LABELS[SPE_FRIGATE] = 'UI/Industry/Specialities/Frigate'
SPE_LABELS[SPE_INTERCEPTOR] = 'UI/Industry/Specialities/Interceptor'
SPE_LABELS[SPE_INTERDICTOR] = 'UI/Industry/Specialities/Interdictor'
SPE_LABELS[SPE_SHUTTLE] = 'UI/Industry/Specialities/Shuttle'
SPE_LABELS[SPE_BATTLECRUISER] = 'UI/Industry/Specialities/Battlecruisers'
SPE_LABELS[SPE_COMMAND_SHIP] = 'UI/Industry/Specialities/CommandShip'
SPE_LABELS[SPE_CRUISER] = 'UI/Industry/Specialities/Cruiser'
SPE_LABELS[SPE_INDUSTRIAL_SHIPS] = 'UI/Industry/Specialities/IndustrialShips'
SPE_LABELS[SPE_INDUSTRIAL_COMMAND_SHIPS] = 'UI/Industry/Specialities/IndustrialCommandShips'
SPE_LABELS[SPE_HEAVY_ASSAULT_CRUISERS] = 'UI/Industry/Specialities/HeavyAssaultCruisers'
SPE_LABELS[SPE_HEAVY_INTERDICTION_CRUISERS] = 'UI/Industry/Specialities/HeavyInterdictionCruisers'
SPE_LABELS[SPE_LOGISTICS] = 'UI/Industry/Specialities/Logistics'
SPE_LABELS[SPE_MINING_BARGE] = 'UI/Industry/Specialities/MiningBarges'
SPE_LABELS[SPE_RECON_SHIPS] = 'UI/Industry/Specialities/ReconShips'
SPE_LABELS[SPE_STRATEGIC_CRUISER] = 'UI/Industry/Specialities/StrategicCruiser'
SPE_LABELS[SPE_BATTLESHIP] = 'UI/Industry/Specialities/Battleship'
SPE_LABELS[SPE_BLACK_OPS] = 'UI/Industry/Specialities/BlackOps'
SPE_LABELS[SPE_MARAUDER] = 'UI/Industry/Specialities/Marauder'
SPE_LABELS[SPE_CAPITAL_INDUSTRIAL_SHIP] = 'UI/Industry/Specialities/CapitalIndustrialShip'
SPE_LABELS[SPE_CARRIER] = 'UI/Industry/Specialities/Carrier'
SPE_LABELS[SPE_DREADNOUGHT] = 'UI/Industry/Specialities/Dreadnought'
SPE_LABELS[SPE_FREIGHTERS] = 'UI/Industry/Specialities/Freighters'
SPE_LABELS[SPE_SUPERCARRIER] = 'UI/Industry/Specialities/Supercarrier'
SPE_LABELS[SPE_TITAN] = 'UI/Industry/Specialities/Titan'
SPE_LABELS[SPE_CAP_DRAIN_DRONE] = 'UI/Industry/Specialities/CapDrainDrone'
SPE_LABELS[SPE_EW_DRONE] = 'UI/Industry/Specialities/EWDrone'
SPE_LABELS[SPE_STASIS_WEBIFYING_DRONE] = 'UI/Industry/Specialities/StasisWebifyingDrone'
SPE_LABELS[SPE_COMBAT_DRONE] = 'UI/Industry/Specialities/CombatDrone'
SPE_LABELS[SPE_FIGHTER_BOMBER] = 'UI/Industry/Specialities/FighterBomber'
SPE_LABELS[SPE_FIGHTER_DRONE] = 'UI/Industry/Specialities/FighterDrone'
SPE_LABELS[SPE_LOGISTICS_DRONE] = 'UI/Industry/Specialities/LogisticDrone'
SPE_LABELS[SPE_MINING_DRONE] = 'UI/Industry/Specialities/MiningDrone'
SPE_LABELS[SPE_SALVAGE_DRONE] = 'UI/Industry/Specialities/SalvageDrone'
SPE_LABELS[SPE_ARMOR_ACTIVE_MODULES] = 'UI/Industry/Specialities/ArmorActiveModules'
SPE_LABELS[SPE_ARMOR_PASSIVE_EXPANDERS] = 'UI/Industry/Specialities/ArmorPassiveExpanders'
SPE_LABELS[SPE_ARMOR_PASSIVE_RESISTANCE] = 'UI/Industry/Specialities/ArmorPassiveResistance'
SPE_LABELS[SPE_SHIELD_ACTIVE_MODULES] = 'UI/Industry/Specialities/ShieldActiveModules'
SPE_LABELS[SPE_SHIELD_PASSIVE_RECHARGE] = 'UI/Industry/Specialities/ShieldPassiveRecharge'
SPE_LABELS[SPE_SHIELD_PASSIVE_RESISTANCE] = 'UI/Industry/Specialities/ShieldPassiveResistance'
SPE_LABELS[SPE_SHIELD_PASSIVE_EXTENDERS] = 'UI/Industry/Specialities/ShieldPassiveExtenders'
SPE_LABELS[SPE_ECM_ECCM] = 'UI/Industry/Specialities/ECMECCM'
SPE_LABELS[SPE_ENERGY_DRAIN_MODULES] = 'UI/Industry/Specialities/EnergyDrainModules'
SPE_LABELS[SPE_TRACKING_DISRUPTOR] = 'UI/Industry/Specialities/TrackingDisruptor'
SPE_LABELS[SPE_WARP_SCRAMBLING_MODULES] = 'UI/Industry/Specialities/WarpScramblingModules'
SPE_LABELS[SPE_DAMAGE_AMPLIFIERS] = 'UI/Industry/Specialities/DamageAmplifiers'
SPE_LABELS[SPE_ENERGY_WEAPON] = 'UI/Industry/Specialities/EnergyWeapon'
SPE_LABELS[SPE_HYBRID_WEAPON] = 'UI/Industry/Specialities/HybridWeapon'
SPE_LABELS[SPE_MISSILE_LAUNCHERS] = 'UI/Industry/Specialities/MissileLaunchers'
SPE_LABELS[SPE_PROJECTILE_WEAPON] = 'UI/Industry/Specialities/ProjectileWeapon'
SPE_LABELS[SPE_SMART_BOMB] = 'UI/Industry/Specialities/SmartBomb'
SPE_LABELS[SPE_CAPACITOR_ACTIVE] = 'UI/Industry/Specialities/CapacitorActive'
SPE_LABELS[SPE_CAPACITOR_PASSIVE] = 'UI/Industry/Specialities/CapacitorPassive'
SPE_LABELS[SPE_CAPITAL_MODULES] = 'UI/Industry/Specialities/CapitalModules'
SPE_LABELS[SPE_DAMAGE_CONTROL] = 'UI/Industry/Specialities/DamageControl'
SPE_LABELS[SPE_FITTING_MODULES] = 'UI/Industry/Specialities/FittingModules'
SPE_LABELS[SPE_HULL_MODULES] = 'UI/Industry/Specialities/HullModules'
SPE_LABELS[SPE_CLOAKING_DEVICE] = 'UI/Industry/Specialities/CloakingDevice'
SPE_LABELS[SPE_JUMP_MODULES] = 'UI/Industry/Specialities/JumpModules'
SPE_LABELS[SPE_PROPULSION_MODULES] = 'UI/Industry/Specialities/PropulsionModules'
SPE_LABELS[SPE_STASIS_WEB] = 'UI/Industry/Specialities/StasisWeb'
SPE_LABELS[SPE_STABILIZER_MODULES] = 'UI/Industry/Specialities/StabilizerModules'
SPE_LABELS[SPE_FLEET_COORDINATOR] = 'UI/Industry/Specialities/FleetCoordinator'
SPE_LABELS[SPE_REMOTE_MODULES] = 'UI/Industry/Specialities/RemoteModules'
SPE_LABELS[SPE_TARGETING_MODULES] = 'UI/Industry/Specialities/TargetingModules'
SPE_LABELS[SPE_TRACKING_MODULES] = 'UI/Industry/Specialities/TrackingModules'
SPE_LABELS[SPE_TRACTOR_BEAM] = 'UI/Industry/Specialities/TractorBeam'
SPE_LABELS[SPE_DRONE_OPERATION_MODULES] = 'UI/Industry/Specialities/DroneOperationModules'
SPE_LABELS[SPE_DRONE_EFFECTIVENESS_MODULES] = 'UI/Industry/Specialities/DroneEffectivenessModules'
SPE_LABELS[SPE_HARVESTING_MODULES] = 'UI/Industry/Specialities/HarvestingModules'
SPE_LABELS[SPE_SCANNING_MODULES] = 'UI/Industry/Specialities/ScanningModules'
SPE_LABELS[SPE_SURVEYING_MODULES] = 'UI/Industry/Specialities/SurveyingModules'
